### ISSUE TITLE
Refactor Supply Liquidity Flow

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1010]
See this below comment. The transaction confirmation going to ledger is way too slow.

https://github.com/balancednetwork/balanced-network-interface/pull/770#issuecomment-1166205102

**Comment by BennyOptions** [comment]
You can see from below videos that supplying liquidity process is a lot slower now. It is so slow, it is not even possible to have two transactions pending at the same time. The prompt on ledger to confirm transaction does not even appear until long after the first transaction is confirmed.

Before the LP token staking upgrade:
https://user-images.githubusercontent.com/43685868/176815720-ce0b3ff0-e693-4353-9589-a7c444f20794.mov

After upgrade:
https://user-images.githubusercontent.com/43685868/176815766-91145514-9d55-4471-9cf1-cd6470c91a82.mov

**Comment by BennyOptions** [comment]
This is what it used to look like before the upgrade


https://user-images.githubusercontent.com/43685868/176815932-0b28855a-3b43-4ac5-97ec-265fd7d734f4.mov

**Comment by octocat512** [comment]
The `usePools` hook was deprecated. Don't use the `usePools`  hook. Please find a solution to implement the LP staking with existing functions. @RiseBlock
