### ISSUE TITLE
Remove liquidity minimum

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1012]
Remove the logic that stops people from supplying less than 10 tokens of liquidity. see comment for details

https://github.com/balancednetwork/balanced-network-interface/pull/770#issuecomment-1166313913

**Comment by molly-tran** [comment]
you want to remove liquidity minimun ?? so how is minQuoteTokenAmount calculated for the first time supply

**Comment by RiseBlock** [comment]
@molly-tran please just remove `minQuoteTokenAmount`, minimum supply rule will be removed
