### ISSUE TITLE
Too many decimal points under "Your Supply"

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1014]
@parrot9design how many decimals do you want here. Currently it's 6, probably too many.

![decimals](https://user-images.githubusercontent.com/43685868/175785877-0144ad36-83d5-4dd1-8ff7-a5cfdbc03b37.jpg)

**Comment by parrot9design** [comment]
Yeah 6 is way too excessive. 2 should be enough, no?

**Comment by molly-tran** [comment]
@BennyOptions please confirm help me

> Yeah 6 is way too excessive. 2 should be enough, no?

**Comment by BennyOptions** [comment]
Agree that 2 is sufficient
