### ISSUE TITLE
Fix bug with input fields on the Trade page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1024]
When using Balanced on mobile, the % bar often hovers in the wrong place when you tap an input field, so it blocks your ability to view the amount:

<img width="400px" src="https://user-images.githubusercontent.com/63842577/176318221-568c6cb8-2f1a-448e-87c4-7b79735c5bc5.jpeg"> <img width="400px" src="https://user-images.githubusercontent.com/63842577/176318233-20ffacd4-b4af-4637-9571-4310541aa20e.jpeg">

**Comment by hetfly** [comment]
@parrot9design resolved in https://github.com/balancednetwork/balanced-network-interface/pull/1042
