### ISSUE TITLE
Supply Liquidity: Remove sICX from supply liquidity modal in the sICX : ICX pair

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#103]
This is only supplying ICX, so remove the sICX part

<img width="433" alt="Screen Shot 2021-03-28 at 4 27 51 PM" src="https://user-images.githubusercontent.com/43685868/112767076-a9dac600-8fe2-11eb-8055-ec44e07dd20b.png">

**Comment by tuan-tl** [comment]
Updated with this PR https://github.com/balancednetwork/balanced-network-interface/pull/114
