### ISSUE TITLE
Change from Solidwallet to icon.community

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1033]
Let's change the RPC endpoint from solidwallet to api.icon.community

**Comment by shallcdn** [comment]
Hi @BennyOptions
For mainnet we'll change the RPC endpoint from https://ctz.solidwallet.io/api/v3 to https://api.icon.community/api/v3, Am I correct?

How about the testnets? We keep current RPC endpoints and only change it on mainnet. Right?

**Comment by BennyOptions** [comment]
@shallcdn you are correct for main net. Testnet I am not sure, @robcxyz do you have testnet endpoints available as well?

**Comment by BennyOptions** [comment]
Please proceed with main net in the mean time

**Comment by BennyOptions** [comment]
done

**Comment by robcxyz** [comment]
> @shallcdn you are correct for main net. Testnet I am not sure, @robcxyz do you have testnet endpoints available as well?

Sorry I missed this. Yes all testnets are covered as well. 

- api.berlin.icon.community
- api.lisbon.icon.community
- api.sejong.icon.community

If we can find someone to replicate the error with security settings, would be good to do some testing on those testnets.
