### ISSUE TITLE
Vote tab: New collateral types

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1045]
need to make a proposal UI for new collateral types.

@dbrehmer what fields should user enter?

**Comment by BennyOptions** [comment]
@parrot9design this will be the fields needed to create the vote:

1.) Debt ceiling (max amount of bnUSD that can be minted using this collateral type)
2.) Liquidation LTV
3.) Lock LTV
4.) Collateral Token Address
5.) Oracle Type (DEX vs Band)
6.) If DEX, select a pool ID
7.) If BAND, enter the ticker of the token (i.e. ETH)

**Comment by parrot9design** [comment]
**Proposal type:** New collateral type
(viewable here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/vote/new-proposal/)

**Custom input fields:**
<img width="1003" alt="Screen Shot 2022-08-15 at 4 55 33 PM" src="https://user-images.githubusercontent.com/63842577/184578802-79d34155-1e15-4a85-ad2b-c3cf64349ee5.png">
- If `Oracle type` = `Band`, change the input label to `Ticker`.
- We can provide error messaging, but not sure what level of error detection would make sense here, i.e. should the UI prevent the liquidation LTV from being under a certain amount, or the debt ceiling or borrow LTV from being too high? Any thoughts here, @BennyOptions?

**Read-only variation:**
(viewable here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/vote/proposal/)
<img width="1062" alt="Screen Shot 2022-08-15 at 5 03 51 PM" src="https://user-images.githubusercontent.com/63842577/184579437-c0308b53-d350-470a-aaf5-2507e46c0d74.png">

If `Oracle type` = `DEX`, we should display the specific liquidity pool underneath, as shown above.

Note that the tooltips don't work on this page, but are available in the code.

---

The `New collateral` proposal type should be published in the multi-collateral release.

The `Loan-to-value ratio` proposal type will also need updated to become `Adjust collateral type` instead, but it's less of a priority, so will post the details for that in a separate issue soon.
