### ISSUE TITLE
Supply Liquidity: sICX / ICX Pair Failure

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#105]
It appears you might be calling the wrong contract or creating the incorrect transaction? 

This is what I clicked when the transaction was initiated
<img width="429" alt="Screen Shot 2021-03-28 at 4 39 48 PM" src="https://user-images.githubusercontent.com/43685868/112767370-66815700-8fe4-11eb-8cd8-4d0956dcd9b0.png">

This should indicate a transfer of 50,000 ICX, but it says 0. It appears you are accidentally calling sICX transfer rather than ICX transfer based on the failed transaction shared below
<img width="462" alt="Screen Shot 2021-03-28 at 4 39 43 PM" src="https://user-images.githubusercontent.com/43685868/112767418-ac3e1f80-8fe4-11eb-8903-83d66e011450.png">

Failed transaction result of insufficient balance despite having enough ICX
https://bicon.tracker.solidwallet.io/transaction/0xb629b396a786683bd50d58f4fa879820e8be948c23167ac2f239b4a17276af2f

**Comment by tuan-tl** [comment]
Fix with this PR https://github.com/balancednetwork/balanced-network-interface/pull/143
