### ISSUE TITLE
Fix base/quote currency display

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1050]
This pair is backwards. bnUSD should NEVER be on the left for any pair.

sICX/BALN is also incorrect. It should be BALN/sICX.

<img width="232" alt="Screen Shot 2022-07-28 at 3 11 24 PM" src="https://user-images.githubusercontent.com/43685868/181618912-302a86d0-34e2-4b29-be62-9276e5333317.png">

**Comment by molly-tran** [comment]
Please check help me !
