### ISSUE TITLE
Fix Slider during supply liquidity

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1051]
Bug was introduced. Slider now goes to over 100% of holdings, so it takes the asset that you have less of into the negative.
<img width="371" alt="Screen Shot 2022-07-28 at 3 22 57 PM" src="https://user-images.githubusercontent.com/43685868/181620757-1867071d-c76c-48ad-a458-a5f48f7ca60d.png">

**Comment by shallcdn** [comment]
Can I confirm the expected behaviour for this case:
 1) Prevent user input of the value if it is over the user balance
 2) Keep current behaviour but remove minus character

@BennyOptions I think the first option is better, cause it keeps UI/UX clear, or do you have another expectation?

**Comment by BennyOptions** [comment]
Hey @shallcdn , I agree with option 1. Thanks!

**Comment by BennyOptions** [comment]
@shallcdn I think this issue is actually caused by the same issues as #1050. Currently, this does not happen with sICX/bnUSD pair, which is the only pair not effected by #1050
