### ISSUE TITLE
Incorrect withdraw amounts

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1063]
See attached video and accompanying transaction. The UI said I was getting 1905 bnUSD and 1915 IUSDC, but I received much more.

https://tracker.icon.foundation/transaction/0x7175854c835aa82f640bb924f20f3af08936f43aa3f0c2c447d420d697e1f9ba

https://user-images.githubusercontent.com/43685868/185229023-a4a9b16b-a586-44b8-91a7-cacf56de4448.mov

**Comment by BennyOptions** [comment]
Calculation of the value of an LP token for IUSDC pairs is weird because it has 6 decimals instead of 18.

**Comment by shallcdn** [comment]
@BennyOptions I have tried to investigate this issue but I couldn't reproduce it. Can you help to test it again?
https://user-images.githubusercontent.com/99955678/187033102-73df4fc9-c67c-4acf-86da-91b89f2b1940.mp4

**Comment by BennyOptions** [comment]
@shallcdn you can't reproduce the issue because you are not using IUSDC/bnUSD pool. It is likely caused by the number of decimal points of IUSDC. It is 6 while all others are 18, therefore, the LP token calculation is different. I tested again with IUSDC/bnUSD pool and received the same result on production
