### ISSUE TITLE
Insufficient Balance when supplying Liquidity

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1066]
Please see below video. It should never say "insufficient balance". When using CFT, it behaves correctly. It gives you the maximum possibly supply liquidity amount given the amount of tokens I have. When I use IUSDC, it allows me to go beyond what is possible.

https://user-images.githubusercontent.com/43685868/186571787-56626f88-7cd9-4c3a-915d-7a9210bd7bd2.mov

**Comment by BennyOptions** [comment]
IUSDC only has 6 decimals on the token contract. I assume it is related to incorrect handling of IUSDC decimal places.

**Comment by BennyOptions** [comment]
It also occurs for BALN / bnUSD


https://user-images.githubusercontent.com/43685868/186572698-2f78dedc-f239-46b2-8c31-a8a1e683594c.mov

**Comment by shallcdn** [comment]
Hi @BennyOptions I have tried to test it several times but it didn't happen to me

https://user-images.githubusercontent.com/99955678/187032456-76263db5-5dc0-4fe7-9387-e457b28f2120.mp4

**Comment by BennyOptions** [comment]
Was not merged to production, only main, now merged.
