### ISSUE TITLE
Update the Vote page to support live voting

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1095]
To support the live voting feature, the Vote page needs an upgrade. View the changes in the [development prototype](http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/vote/).

This is the interface at a high level:
![Vote page](https://user-images.githubusercontent.com/63842577/198192792-e7bcc1e8-aae9-48ee-a829-a94ef649f7a2.png)

---

The Voting Power section is similar to the Boost Rewards section on the Home page, but with different content and datapoints:
![Voting power section](https://user-images.githubusercontent.com/63842577/198190914-4309ebf6-d4c8-4c2e-989d-ae69b245f5e3.png)

---

The Proposal section displays the last 3 proposals. Click `View all` to view the full list of proposals, similar to how the Vote page currently works.
![Proposals](https://user-images.githubusercontent.com/63842577/198191186-0ba2d393-ac43-45ba-ae55-91e6d1cb8fed.png)

---

## Liquidity incentives
The Liquidity Incentives section is where live voting takes place. When you're signed out or don't hold bBALN, this is what you'll see:
![liquidity incentives - signed out](https://user-images.githubusercontent.com/63842577/198192859-1a62b352-e51a-4bd7-bd8c-16343962d730.png)
 

When you have bBALN, you'll see the addition of a `Your allocation` column. It should reflect the current allocation until you choose to adjust it. 
![liquidity incentives - ready to adjust](https://user-images.githubusercontent.com/63842577/198192986-ece0ef89-2cad-4627-9376-c93552b1b571.png)

When you click Adjust, you can choose the percentage to allocate to each:
![liquidity incentives - adjust state](https://user-images.githubusercontent.com/63842577/198194803-b2ae2fa9-d08f-4474-af32-6f7abce28f58.png)

And if the amount is too much or too little, a message will be displayed above the inactive Confirm button:
![liquidity incentives - too much](https://user-images.githubusercontent.com/63842577/198194922-84699fe2-b4b2-4750-992c-cfc3a9d5afa6.png)

When you click Confirm, you'll see this confirmation modal:
![confirmation modal](https://user-images.githubusercontent.com/63842577/198216415-1f607cff-6dbe-4311-95e3-44c49064aee8.png)

The transaction messages should be:

> Adjusting your liquidity allocation...

> Adjusted your liquidity allocation.

> Couldn't adjust your liquidity allocation.

The `Your allocation` and `Current allocation` tooltips also include countdown timers for easy reference:
![Screen Shot 2022-10-27 at 5 54 54 PM](https://user-images.githubusercontent.com/63842577/198195349-88602aa9-2481-4c1c-b71b-2ad9b312516b.png) ![Screen Shot 2022-10-27 at 5 55 01 PM](https://user-images.githubusercontent.com/63842577/198195354-0d2be1ee-b17c-494d-be59-c679442be96f.png)

**Comment by AntonAndell** [comment]
There are some discrepancies here between design and curve voting implementation. 
A vote is for a single source and the voting lock of 10 days is also per source.
A User votes a percentage for a source and then those percentages are locked for that source for 10 days. The remaining percentages can still be used on other sources. 

This could perhaps be modified on the smart contract side but not sure if there would be any problems.

**Comment by parrot9design** [comment]
Interesting, thanks for bringing that to our attention! Do you think a change on the smart contract side is feasible, or should we go ahead and rework the UI? The existing design would be the most straightforward, but we can make it work.

**Comment by AntonAndell** [comment]
After some quick discussion we would prefer to not stray from the curve design. If it helps we can introduce a function to vote for multiple sources in the same transaction and thus giving them the same unlock time. But not sure it that would just end up being more confusing if the design incorporates separate timers

**Comment by parrot9design** [comment]
The Liquidity Incentives design has been updated to support per-pool adjustments (affects signed-in state only).

The amount of voting power you have to allocate is displayed in the top right:
<img width="1050" alt="Screen Shot 2022-11-15 at 4 57 08 PM copy" src="https://user-images.githubusercontent.com/63842577/201823447-0684b49a-240d-4bbf-8301-d2af426d2851.png">

---

To adjust your allocation, click `Add` or the edit button next to a pool, then enter the % you want to allocate to it. (We should display the % symbol, but not require users to enter it.):

<img width="1063" alt="Screen Shot 2022-11-15 at 4 51 29 PM" src="https://user-images.githubusercontent.com/63842577/201824064-a9299e02-c9ba-4396-b9c1-167b510b4434.png">

If you allocate too much, the values for the input box and voting power available should go red, and the Confirm button should be inactive:

<img width="1050" alt="Screen Shot 2022-11-15 at 5 10 58 PM" src="https://user-images.githubusercontent.com/63842577/201824622-e2c84b33-97dc-4c4d-b3d4-b8b9a7b9b431.png">

---

When the amount is within the limits, click Confirm to trigger a confirmation modal:
<img width="411" alt="Screen Shot 2022-11-15 at 5 04 09 PM" src="https://user-images.githubusercontent.com/63842577/201823749-13f949e3-b448-4a10-a629-00ee21668054.png">

---

Your allocation for that pool will be updated, and a tooltip will appear alongside the value. Hover over it to see the amount of time remaining until you can adjust it:
<img width="1063" alt="Screen Shot 2022-11-15 at 4 57 15 PM" src="https://user-images.githubusercontent.com/63842577/201823894-ac1c084d-95da-4da2-9481-a2a823ce388e.png">

When time runs out, the edit icon replaces the tooltip.
