### ISSUE TITLE
Liquidity Details: Withdraw Liquidity

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#110]
Issue 1: It is not possible to type into the text box

Issue 2: The slider does not work

<img width="346" alt="Screen Shot 2021-03-28 at 5 50 16 PM" src="https://user-images.githubusercontent.com/43685868/112769268-2626d680-8fee-11eb-9460-8311ec5fd241.png">

**Comment by tuan-tl** [comment]
Close as duplicated with this issue https://github.com/balancednetwork/balanced-network-interface/issues/150
