### ISSUE TITLE
bBALN amount discrepency

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1104]
See screenshot, showing two different amounts of bBALN. This happened right after locking more, but also persisted post-refresh.

<img width="324" alt="Screen Shot 2022-11-01 at 11 27 54 PM" src="https://user-images.githubusercontent.com/43685868/199388725-2c8bbc5c-30e5-4971-83f0-b79ced7023ef.png">

**Comment by hetfly** [comment]
@BennyOptions I don't think there is anything wrong here. 

Number below the slider shows the amount of locked BALN, number above the slider shows the actual bBALN value based on the locked BALN and it's duration.

There are two reasons user will never have bBALN equal to locked BALN.

1) It's possible to lock until certain checkpoints, those checkpoints are every Thursday 0:00 UTC. So if user locks on Tuesday for a week, the lock duration is only ~2 days.

2) The maximum lock amount used in bBALN calculation isn't divisible by weeks, meaning there will always be few days 'cut off' of the bBALN amount.

**Comment by BennyOptions** [comment]
got it, thanks and makes sense!
