### ISSUE TITLE
Loans does not refresh when changing wallets

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1106]
When I change wallets, the UI does not update the following sections:

- Collateral
- Loan
- Position Details

So, for example, if I am logged in with hx1 and hx1 has an open loan with collateral of 500 sICX and a Loan of 10 bnUSD, when I switch wallet to hx2, which has no loan and no collateral, it still displays collateral = 500 sICX and Loan = 10 bnUSD. This is only fixed by refreshing the page. Changing to Trade page or even vote page does not update those sections. This has been happening for a very long time, just never made an issue.

**Comment by hetfly** [comment]
duplicate https://github.com/balancednetwork/balanced-network-interface/issues/1124
