### ISSUE TITLE
Decimal Issue with IUSDT and IUSDC Fee APY

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1122]
See screenshot from Incentivized Pools section on the Trade tab
![Screen Shot 2022-12-05 at 3.33.12 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/80caf4f3-6907-4600-a1e4-fe0a9bbd7e0c)

**Comment by AntonAndell** [comment]
We did a smart contract fix so data should be back to normal withing 24H and 30days  
on both endpoints. However that data will still remain faulty and has to be removed or ignored somehow if it where to cause any other issues

**Comment by hetfly** [comment]
There is now check to hide apys > 10000% before the data comes back to normal
