### ISSUE TITLE
Improve the transfer flow for IRC2 tokens

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1136]
IRC2 tokens being transferred from ICON to BSC don't require approval, and are instead moved to the BTS contract in the first transaction. We should improve the user flow to prevent people getting into a state where the assets have been moved to the contract, but the transfer hasn't been completed.

For IRC2 tokens (ICON -> BSC only):

- [x] Change the button in the confirmation modal from `Approve` to `Send to contract`. This sets the expectation that the asset will be removed from the wallet, as people aren't going to expect that from an approval transaction.

<img width="431" alt="Screen Shot 2022-12-19 at 8 05 52 PM" src="https://user-images.githubusercontent.com/63842577/208368672-9ae66a76-9d5e-4cb5-ad9a-c9715f8801dd.png">

- [x] After the asset has been sent to the contract, display a `Remove from contract` text link:

<img width="438" alt="Screen Shot 2022-12-19 at 8 33 55 PM" src="https://user-images.githubusercontent.com/63842577/208371814-67e78a7c-3dcd-49dc-9c89-6d9299ab985a.png">

---
 

- [x] If a user sends their asset to the contract but fails to complete the transfer, we should make it as easy as possible to take action when they come back to the Transfer UI. After they choose their wallet and the relevant asset, we should either:

1. Present them with the confirmation modal above to complete the transfer or remove the assets from the contract (use this option iif we can retrieve the original transfer address), or
2. Update the message displayed in the Transfer UI below to `{amount} {asset} is awaiting transfer. Enter an address to complete the transaction.`:

<img width="539" alt="Screen Shot 2022-12-19 at 8 00 12 PM" src="https://user-images.githubusercontent.com/63842577/208819459-836d1cd2-47a9-4f2b-8e4e-6893b2a71929.png">

**Comment by trieuvo212** [comment]
Pull request 1219: It is currently going through option 2 when user doesn't finish the transfer:
- The message `{amount} {asset} is awaiting transfer. Enter an address to complete the transaction.` hasn't been updated.
- When user inputs another address, the transfer button is still disabled and cannot be chosen. Suggest: change to option 1 or prefill the previous address or allow to input another address.
![image](https://github.com/balancednetwork/balanced-network-interface/assets/43066076/5fb0d792-ed51-45d7-ab31-2dd237d77213)

**Comment by bam-21** [comment]
Pull request #1219: It is currently going through option 2 when user doesn't finish the transfer:

- The message `{amount} {asset} is awaiting transfer. Enter an address to complete the transaction.` hasn't been updated.
- When user inputs another address, the transfer button is still disabled and cannot be chosen. Suggest: change to option 1 or prefill the previous address or allow to input another address.
![image](https://github.com/balancednetwork/balanced-network-interface/assets/139465421/be7c5fe1-b21c-4b70-9e6a-fe04f6274bae)
