### ISSUE TITLE
Cross-chain transfer "Max" causes issues

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1166]
When clicking the max button, the UI gets stuck on "Approve", can't move forward.

**Comment by BennyOptions** [comment]
https://user-images.githubusercontent.com/43685868/222333928-0f324746-2016-42eb-911f-24ca975eae54.mov

**Comment by Chunn** [comment]
@BennyOptions (@RiseBlock ) I can not reproduce this bug. Could you give me more information?
Such as: what browser? Did you do anything before the cross-chain transfer? Did you have any incomplete transactions?

Thank you!

https://user-images.githubusercontent.com/17588370/222788663-a0f3cc4b-33ec-404d-bd6f-ec78530bfa55.mov

**Comment by BennyOptions** [comment]
Hey @Chunn this happens using firefox and google chrome. I took no other actions before initiating the transfer. It could be a main net issue. Try on main net if you can with a small amount of coins.

**Comment by Chunn** [comment]
@BennyOptions (@RiseBlock ) I've tried to check based on the main net on google chrome. But I still can not reproduce this bug 😞. Please check the attached video:

https://user-images.githubusercontent.com/17588370/224496767-5962928f-68c4-41fc-ac11-1b3c9e0ba709.mov

Could you help me check this bug again? Is it still happening?

**Comment by BennyOptions** [comment]
@Chunn I have tried again from google chrome and had no issue like you showed. Maybe there was some conflict that was resolved in a recent PR on accident, or maybe I will find the issue again in the future. For now, I will close this issue, thanks for your time!
