### ISSUE TITLE
Number of the amount waiting transfer is include fee

### ISSUE THREAD

**Issue by mangcanbang** [balancednetwork/balanced-network-interface#1226]
Step to reproduce
- I sent to contract 1 bnUSD
- The fee = 1.5 bnUSD
- I close the transfer popup
- The message is  2.5 bnUSD is waiting transfer, remove it from the bridge contract
- When I remove it from contract, the toast message show that I removed 1 bnUSD

So I wonder if we need to include fee in the message or not, because we actually remove 1 bnUSD, not 2.5 bnUSD
<img width="1344" alt="Screenshot 2023-07-29 at 17 05 19" src="https://github.com/balancednetwork/balanced-network-interface/assets/140887024/a21082fc-f954-40e0-85af-bd5f7ab687c0">

**Comment by parrot9design** [comment]
When I tried this a few days ago, the amount sent to the contract included the fee, which would mean the notification message is showing the wrong amount. Will test this out with a few more tokens to confirm, though.

Are you testing via app.balanced.network or the development previews in #1219? If the latter, it would be best to post your feedback there so it's easier to keep track of.
