### ISSUE TITLE
Only IRC2 token can remove sent amount from bridge contract

### ISSUE THREAD

**Issue by mangcanbang** [balancednetwork/balanced-network-interface#1227]
I sent my token from ICON => BNB SC
I cannot remove tokens (BNB, BUSD, USDT, USDC, BTCB, ETH) from the bridge contract after I sent it to the contract .

**Comment by parrot9design** [comment]
@mangcanbang were you using the transfer UI through app.balanced.network, or the latest deployment in https://github.com/balancednetwork/balanced-network-interface/pull/1219 (where we're actively addressing this issue)?
