### ISSUE TITLE
The balance of user is not correct in testnet

### ISSUE THREAD

**Issue by mangcanbang** [balancednetwork/balanced-network-interface#1228]
I use Lisbon testnet and I have ICX but the UI not show that
<img width="1431" alt="Screenshot 2023-07-30 at 23 03 52" src="https://github.com/balancednetwork/balanced-network-interface/assets/140887024/d1c845e6-f18c-435c-acd8-33ba8563e529">
<img width="1431" alt="Screenshot 2023-07-30 at 23 03 59" src="https://github.com/balancednetwork/balanced-network-interface/assets/140887024/ad90efd7-f053-426c-a26d-e5c4144ea183">

**Comment by hetfly** [comment]
Screenshot provided shows that the app runs on mainnet. Selected chain in the Hana wallet doesn't affect the UI chain.

here is a testnet version https://test.balanced.network/
