### ISSUE TITLE
Front end Injective integration

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1242]
Preparation: (evm template must investigate whats needed for Injective)

what assets are on the chain?
XCall, AssetManager, bnUSD addresses? xChainId of the chain.
Update Manage wallets modal design for several EVM chains.
Todo:

Add xChainId and assets on xTokenMap
Update Manage wallets modal UI
Add the EVM Chain to Wallet UI
Add the EVM chain native token as collateral on the Home page
Fetch balances
Problems:

Switching chains

Wallets to support
Keplr 
Hana
Ninja waller https://docs.ninji.xyz/integrate-ninji-wallet/dev-guide-injective-dapps-integration

**Comment by FezBox** [comment]
Being Picked up this week. First got to research the chain then will get estimates

**Comment by FezBox** [comment]
2 weeks form today - pull request to review
