### ISSUE TITLE
Hide the `Liquidity details` section when no liquidity is supplied

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#126]
<img width="806" alt="Screen Shot 2021-03-31 at 12 58 49 PM" src="https://user-images.githubusercontent.com/63842577/113071296-ec89e180-9220-11eb-8bff-5a9b37738eb3.png">

You shouldn't be able to see the `Liquidity details` section unless you're signed in and have supplied liquidity.

**Comment by tuan-tl** [comment]
Fixed with this commit https://github.com/balancednetwork/balanced-network-interface/commit/88fd1c31289031001501146847bd27dddddddd8b
