### ISSUE TITLE
Update the ICON Bridge link + tweak some microcopy

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1280]
The link to learn more about ICON Bridge is out of date. Let's update it to https://docs.balanced.network/transfer-cross-chain#icon-bridge
![NKoxO5PQ](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/39e74335-ebc2-4315-a8ee-54e6e290b928)

---

While we're here, I also want to make another adjustment to the Rewards section (I know, sorry! 😅):

- Change `Earning power` -> `Earning potential`
- Adjust the tooltip content to fit: `Your earning potential depends on...`

**Comment by parrot9design** [comment]
Another piece to add to this:

The preview card isn't loading in when shared on social. The link should be absolute instead of `/img/...`. This image still has only 2 pages (yikes), so let's replace it with this one:
![home](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/bacc1a81-cb87-4a0d-b41e-0119093df3b2)

**Comment by hetfly** [comment]
@parrot9design can you re-upload the image please? Can't download it

**Comment by parrot9design** [comment]
Try this: 
[home.png.zip](https://github.com/balancednetwork/balanced-network-interface/files/14485221/home.png.zip)

**Comment by hetfly** [comment]
That works, thanks!
