### ISSUE TITLE
Remove legacy tokens from swap

### ISSUE THREAD

**Issue by CyrusVorwald** [balancednetwork/balanced-network-interface#1293]
BUSD is no longer supported by Binance. https://www.binance.com/en/feed/post/1131844
BUSD should no longer be listed under swaps because it is no longer maintained, and it being listed can give off the impression that Balanced is no longer maintained either.
There may be other assets that should also be removed, I'm not that familiar with all of the assets in the list.

**Comment by swiftcc624** [comment]
https://github.com/balancednetwork/balanced-network-interface/pull/1309

**Comment by FezBox** [comment]
@hetfly, are we waiting on anything for this to be merged?
