### ISSUE TITLE
Borrowing bnUSD in the app states there is interest but the marketing pages state there is no interest

### ISSUE THREAD

**Issue by CyrusVorwald** [balancednetwork/balanced-network-interface#1295]
If I borrow bnUSD on the application, it says there is interest:

![image](https://github.com/balancednetwork/balanced-network-interface/assets/90732384/e468cb5d-fd99-4bcc-8e06-13947ee5a276)

But on the marketing pages, it says there is no interest:

https://balanced.network/ says "You can borrow Balanced Dollars for a one-off, 0.2% fee (no interest) or buy some on the Balanced exchange."

https://balanced.network/stablecoin/ says "It’s interest-free, so you’ll only pay a one-off, 0.2% fee."

https://docs.balanced.network/borrow-bnusd says there is 2% interest

**Comment by parrot9design** [comment]
Thanks. We are aware of this and will have an update pushed to the website soon.
