### ISSUE TITLE
Clicking on archway in the wallet dropdown does not do anything

### ISSUE THREAD

**Issue by CyrusVorwald** [balancednetwork/balanced-network-interface#1298]
The cursor changes to a pointer but clicking does not perform any action.

![image](https://github.com/balancednetwork/balanced-network-interface/assets/90732384/4806492b-a2a7-4a5c-8875-2a6989624153)

**Comment by parrot9design** [comment]
Clicking on Archway in the wallet dropdown should show your Archway wallet address and the assets in your Archway wallet. From your screenshot, it appears that it's working as expected.

**Comment by BennyOptions** [comment]
Yeah @CyrusVorwald maybe u can do a screen record if there's still something u want to point out. Hard to see the issue based on this screenshot

With archway selected, it is supposed to show ur archway assets. If u click ICON, it'll switch to show icon assets only

**Comment by CyrusVorwald** [comment]
The screenshot didnt show my mouse cursor. If I hover over the sARCH part of it, my mouse cursor turns to a pointer, but clicking on the button does not do anything. https://www.loom.com/share/ab34e0af6d484888aa66fbd14512d466

**Comment by parrot9design** [comment]
Ah! I see, it's the assets themselves that are the issue. Thanks for that clarification.

Currently, the wallet only allows you to manage ICON-based assets. You can't send assets from other chains, so they're read-only. @hetfly remind me: was this something we can support after the xCall refactor without extensive effort, or do we need to add an indicator for assets that can be managed?

**Comment by CyrusVorwald** [comment]
If they're read-only, they should not have a cursor pointer because that implies if I click on it that something will happen.

**Comment by parrot9design** [comment]
Yes, that obviously needs to be fixed. However, we also need to consider mobile users, who don't get that affordance.

**Comment by hetfly** [comment]
@0xmilktea for now just remove the pointer cursor style from non ICON wallets

**Comment by swiftcc624** [comment]
@hetfly here is the pr - https://github.com/balancednetwork/balanced-network-interface/pull/1305
