### ISSUE TITLE
Fix input field styles

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#13]
Some fields have styles that suggest they're interactive, even though they're not. 

* [x] Remove the token selector style from the Send tab, Withdraw tab, and Return bnUSD tab.

<img width="300px" src="https://user-images.githubusercontent.com/63842577/110713180-563c4e80-8266-11eb-9e94-7dc47079bdb0.png">![Screen Shot 2021-03-11 at 12 38 16 PM](https://user-images.githubusercontent.com/63842577/110713363-b0d5aa80-8266-11eb-9d02-dd36352684b3.png)![Screen Shot 2021-03-11 at 12 38 40 PM](https://user-images.githubusercontent.com/63842577/110713387-ba5f1280-8266-11eb-823f-d8bd38696d44.png)

* [x] Remove the active border from fields that aren't interactive
![Screen Shot 2021-03-11 at 12 25 02 PM](https://user-images.githubusercontent.com/63842577/110711861-1e80d700-8265-11eb-8022-02f92e56059f.png)![Screen Shot 2021-03-11 at 12 26 43 PM](https://user-images.githubusercontent.com/63842577/110711856-1c1e7d00-8265-11eb-9a45-a6ffdeac2112.png)

Reference the [prototype](https://balanced.network/prototype/) and the [code](https://github.com/balancednetwork/balanced-frontend/tree/development/prototype-final) for the correct styles.

**Comment by gedanziger** [comment]
when you hover, the border means it's interactive. Some fields aren't actually interactive, but have the interactive label.
