### ISSUE TITLE
Redemption Tooltip Fix

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1302]
You should be able to pull this number directly from the contract so it doesn't need to change. It's the sum of two numbers, one of them is getRedemptionFee, not sure what the other is. @AntonAndell will know.

<img width="714" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG4wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fa890cfad28f95b3d888951b25998ca5a4a4ac4/Screenshot%202024-03-20%20at%2012.31.05%20AM.png" alt="Screenshot 2024-03-20 at 12.31.05 AM.png" />

**Comment by AntonAndell** [comment]
The two values are from:
    @External(readonly = true)
    public BigInteger getRedemptionFee()

    @External(readonly = true)
    public BigInteger getRedemptionDaoFee() {

**Comment by BennyOptions** [comment]
![image](https://github.com/balancednetwork/balanced-network-interface/assets/43685868/d630ef14-1309-4ca5-9319-d258523c20b6)
