### ISSUE TITLE
Feedback: Tooltip at savings rate

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1313]
See the below suggestion. As a user I like being able to see the breakdown of what contributes to the x% aggregate reward rate.

<img width="336" alt="Screenshot 2024-04-03 at 12 17 32 AM" src="https://github.com/balancednetwork/balanced-network-interface/assets/43685868/04c482e1-f265-47f4-b42b-955b9ca1bea5">

**Comment by parrot9design** [comment]
I initially thought this would be better suited to the Stats page, but on second thought I'm happy to add it to the Home page.

We can display the tooltip content in both the signed in/out states. While it won't need any special logic, be aware that every other tooltip in this section does.

Tooltip content:

>bnUSD: x%
>sICX: y%
>
>${amount} distributed over the past month.

**Comment by FezBox** [comment]
@parrot9design is this still a valid issue?
