### ISSUE TITLE
Update the wallet to show the balance of all EVM chains

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1351]
Let's update the wallet section (top right) to include all EVM chains tied to the connected wallet.

Apps like Uniswap, Rango Exchange, and Zerion automatically pull in your wallet balance for each EVM chain, even though it's technically only active on one of those chains at a time. We already display the balance of non-active chains in the Swap and Transfer tabs, so it's disorienting when you can't see them tallied in the wallet section.

![337085651-ad331244-0e50-4745-b5c1-7b0256926a24](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/65f8ac9c-1096-4a41-9c73-4c5b9d6ef241)

I'm not sure if this logic has been implemented yet, but here's the mockup of how to handle more than 4 chains in the wallet:
<img width="432" alt="wallet-dropdown-many-chains-2" src="https://github.com/balancednetwork/balanced-network-interface/assets/63842577/0df10970-dccb-4fa7-9353-c995698b19f9">

While working on this, we should also fix the sign-in logic so Balanced only connects to a wallet you've explicitly chosen. If you use Hana in your browser with multiple wallets, every time you view a different wallet in Hana the EVM wallet connected to Balanced will change to match. I'm worried this is going to catch someone out eventually. I can't reproduce this issue in Metamask, but it's possible other wallets are also affected.

**Comment by FezBox** [comment]
https://github.com/balancednetwork/balanced-network-interface/pull/1347
