### ISSUE TITLE
Re-add the ability to supply liquidity for cross-chain assets

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1352]
We should allow liquidity providers to transfer their cross-chain asset to ICON during the liquidity confirmation process. 

To supply liquidity for a cross-chain asset currently, you have to go to the Bridge tab and transfer it to ICON first. In the spirit of "reduce time and effort", we should always strive to make it as simple as possible.

That will require some clarification to make sure people understand their liquidity is tied to an ICON wallet:

![balanced-network-interface-cl39cqlb4-balanced-dao vercel app_trade_supply_AVAX_bnUSD (1)](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/39712725-c7f8-4eba-bcc4-8e47445985c7)

ICON-based liquidity should display this message in the confirmation modal:
> Send your liquidity to Balanced, then click Supply.

<br>

Cross-chain liquidity will also need this message:
> {asset} will be transferred to ICON for a **{amount ticker}** fee, and your ICON wallet will own the liquidity.

**Comment by FezBox** [comment]
@0xmilktea will first research how to complex this is and if there is a way to keep this simple
