### ISSUE TITLE
Improve or remove the banner messages from cross-chain transactions

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1358]
The banner messages for cross-chain transactions report that a transaction is successful when only the first half is complete. It's somewhat confusing at best and alarming at worst.

We should be able to detect when the transaction is fully complete because the UI has to update accordingly. Let's use the same trigger to serve the success messages at the appropriate time,. 

If it's not as easy to implement this as I've assumed, we should remove the messages from all collateral/loan/swap/bridge transactions.

We can leave the messages in place for ICON <> ICON transactions.

**Comment by FezBox** [comment]
@hetfly to estimate the work
