### ISSUE TITLE
Hide the Liquidity Bribes section when there are no upcoming bribes or rewards to claim

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1359]
There are no bribes on offer at the moment. I don't know if/when we plan to offer more BALN incentives or if Craft plans to top up theirs, but we shouldn't keep it in the UI if you can't do anything with it for an extended period of time.

When there are no upcoming bribes and people have none to claim, we should hide the Liquidity Bribes section.

While we're at it, we should also fix the alignment of the `Current incentives` column label.

![Screenshot 2024-06-26 at 9 10 48 AM](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/f271ed19-e364-4ae3-b1b2-751cb9787811)

**Comment by hetfly** [comment]
@FezBox @parrot9design 
I'm closing this issue. There will be some bribes for the next couple of weeks and we will revisit this section during the work on the bribes dashboard anyways.
