### ISSUE TITLE
Fix the Savings Rate tooltip

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1361]
The Savings Rate tooltip was implemented as part of #1355, but I didn’t realise until I got the email saying the issue had been resolved.

It was not well implemented, and needs to be fixed.

On mobile, it’s now spread over 3 lines instead of staying next to the APR value:

![image](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/8358959f-ea2f-4fcf-9630-c96c3746e923) ![image](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/f117abb1-c111-41f5-b6b9-9b0a817356dc)

On desktop, the tooltip icon is not aligned with the content beside it:
![image](https://github.com/balancednetwork/balanced-network-interface/assets/63842577/bd46ba00-bfda-4dd4-9cff-16932c9dc24b)

It also only partially implemented the content provided in #1313:

> bnUSD: x%
> sICX: y%
> 
> ${amount} distributed over the past month.

**Comment by FezBox** [comment]
released this week as well
