### ISSUE TITLE
refactor: swap & bridge code

### ISSUE THREAD

**Issue by 0xmilktea** [balancednetwork/balanced-network-interface#1364]
- use XToken instead of Currency
- reconsider ARCHWAY_FEE_TOKEN_SYMBOLS
- generalize WalletUI, Havah, EVM, ICON

**Comment by 0xmilktea** [comment]
- remove useArchwayWalletBalances, useHavahWalletBalances. and use generalized function to get balances. but keep useICONWalletBalances because the function is used in many places.

**Comment by 0xmilktea** [comment]
- use camelCase for chain_id in providers

**Comment by FezBox** [comment]
This will be worked on after the cross-chain loan review
