### ISSUE TITLE
Add weETH and wstETH tokens to front end 

### ISSUE THREAD

**Issue by FezBox** [balancednetwork/balanced-network-interface#1382]
add weETH and wstETH so it can be used for minting bnusd 
Chains to support it are 

- [ ] arbitrum
- [ ] optimisim
- [ ] Base

**Comment by AntonAndell** [comment]
What price should we use here, will you ask band to add them?

**Comment by 0xExp-po** [comment]
I'm a seasoned blockchain developer with deep knowledge and experience
can I contribute to this project by doing this?
