### ISSUE TITLE
Cross-chain loan enhancements

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#1401]
- [x] Add list sorting to the collateral & blockchain selectors.
- [x] When signed in, order both lists in the collateral section from highest to lowest collateral deposited, then by highest to lowest balance available. Sort the loan blockchain selector by wallet balance.

<br>

- [ ] Add the chain breakdown for each collateral type in the signed out & `All collateral` states:
![Screenshot 2024-08-19 at 1 28 49 PM](https://github.com/user-attachments/assets/b2023b41-595e-41ef-9702-b387b450a0cb)

- [x] Update the zero balance view in the Collateral section to prompt users to add the token to their wallet:
<img width="556" alt="update-0-balance-state" src="https://github.com/user-attachments/assets/afdee277-a71d-464a-812a-3ea6834d6530">

>Add {token} to your {blockchain} wallet.

<br>

- [x] The above screenshot was taken in Firefox. Is there any way to fix the alignment of icons and chevrons on the Home page? Also noticed it on the Trade page, but to a lesser extent.

<br>

- [x] When you click to adjust your collateral/loan, the Confirm button should be inactive until there's a change in balance so that you can't complete empty transactions.
https://github.com/user-attachments/assets/d0d1869f-688f-4774-9d83-35a80ce7900e

<br>

- [x] Hide the blockchain address in the borrow confirmation modal if you choose to receive bnUSD on the same chain.

<br>

- [x] Update the confirmation modals to use `Transfer fee` instead of `Cross-chain fee`:
![Screenshot 2024-08-19 at 4 03 05 PM](https://github.com/user-attachments/assets/bb53d63b-24ef-432a-a6b4-113bfde64ac4)

<br>

- [x] This applies to the whole app, but when you first visit a page, it takes a while for the fonts etc to load in. Is there anything we can do to speed this up?

<br>

- [x] When you choose to withdraw ICX collateral, make `Keep sICX` the default and change `recieve` to `receive`:
<img width="434" alt="Screenshot 2024-08-22 at 5 40 45 PM" src="https://github.com/user-attachments/assets/6e0cb884-c0b5-4d60-8969-7788cb6528c8">

<br>

- [x] Update the social image for the app (https://app.balanced.network/img-preview/home.png) to this one: [home.png.zip](https://github.com/user-attachments/files/16860709/home.png.zip)

<br>

- [x] Update the sign in message in the Collateral section (`... sign in with {chain}.` -> `...sign in on {chain}.`
![update-sign-in-prompt](https://github.com/user-attachments/assets/2949bd97-3f83-488e-918a-50fc7644d2f4)

<br>

- [x] Prevent the borrow fee in the modal from resetting to `0 bnUSD` after you sign the transaction

<br>

- [x] After you click Connect for a chain in the Loan section, that blockchain should become the active one.
https://github.com/user-attachments/assets/d8b812ef-4145-4cef-bb05-97c6612f9393

<br>

- [x] If a transaction has to roll back, let's change the modal message from `Transfer rollbacked` to `Transaction reverted`

**Comment by hetfly** [comment]
>Add the chain breakdown for each collateral type

Still waiting for the backend


>This applies to the whole app, but when you first visit a page, it takes a while for the fonts etc to load in. Is there anything we can do to speed this up?

I've added a `font-display: swap` rule to the font face, that should specifically force loading the font as soon as the rule is read. 

Usually this is handled by preloading the font, but it's kind of loosing the sense in our bundler, because the bundler hashes the asset names. Meaning the resulting font name has a gibberish in the end - `font-name-D34Hhhd77.woff`for example. So we would have to import the files dynamically using javascript, then create the preloading tags using the dynamic names and then append the tags to the document. Doesn't sound like performance optimisation 😅 

The css rule should help, if not and the font change issue is still annoying, I can look into the option above in more detail.
