### ISSUE TITLE
Supply Liquidity: sICX / ICX Pair

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#141]
This pair only requires one transaction - to send ICX to the pool. Please update the UI to look like this

<img width="428" alt="Screen Shot 2021-03-31 at 4 43 13 PM" src="https://user-images.githubusercontent.com/43685868/113208919-654c6600-9240-11eb-99b8-efffb6524655.png">

**Comment by parrot9design** [comment]
Here's how that would look:

![Screen Shot 2021-04-02 at 14 21 07](https://user-images.githubusercontent.com/63842577/113230457-8458ff80-92f5-11eb-87e1-67bd52a3bab0.png)



```
<div class="modal-content">
	<!-- Overview -->
	<h3 class="label text-center">Supply liquidity?</h3>
	<p class="text-bold text-center">100 ICX</p>

	<!-- Fee -->
	<p class="label text-center">Your ICX will be staked as sICX, and locked in the pool for the first 24 hours.</p>
	<!-- Modal actions -->
	<div class="modal-actions">
		<a href="#" class="cancel modal-close">Cancel</a> <a href="./" class="button">Supply</a>
	</div>
</div>
```
