### ISSUE TITLE
cant run the interface locally after following the install instructions

### ISSUE THREAD

**Issue by FidelVe** [balancednetwork/balanced-network-interface#1424]
Good morning team.

Im trying to run the interface locally but im running into many errors. This is what I did:

* `git clone git@github.com:balancednetwork/balanced-network-interface.git`
* `cd balanced-network-interface`
* `pnpm install`
* `cd apps/web`
* tried to run `yarn` and `yarn install` got the following error:
```
Usage Error: This project is configured to use pnpm

$ yarn ...
```

* ran instead `pnpm install` successfully 
* tried running `pnpm run dev` and got the following errors:
```
[plugin:vite:import-analysis] Failed to resolve entry for package "@balancednetwork/sdk-core". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by FezBox** [comment]
@0xmilktea @hetfly can you please respond

**Comment by hetfly** [comment]
Hello @FidelVe 

1. set you working directory to the balanced interface repo root and run
```
pnpm run build
```

2. if that doesn't help, do this
```
pnpm clean
pnpm install
pnpm run build
pnpm run dev
```

3. if it's still not working, make sure you have these package versions
```
node v20.15.1
pnpm v9.5.0
typescript v4.5.2
```
and repeat step 2

**Comment by FidelVe** [comment]
> Hello @FidelVe
> 
>     1. set your working directory to the balanced interface repo root and run
> 
> 
> ```
> pnpm run build
> pnpm run dev
> ```
> 
>     2. if that doesn't help, do this
> 
> 
> ```
> pnpm clean
> pnpm install
> pnpm run build
> pnpm run dev
> ```
> 
>     3. if it's still not working, make sure you have these package versions
> 
> 
> ```
> node v20.15.1
> pnpm v9.5.0
> typescript v4.5.2
> ```
> 
> and repeat step 2

works perfectly, thanks.

The current instructions in the [readme](https://github.com/balancednetwork/balanced-network-interface/tree/master/apps/web#development) of the web app are outdated and dont work, we need to update it with these instructions then

**Comment by FezBox** [comment]
@FidelVe can this be closed?
