### ISSUE TITLE
Injective: bnUSD migration to denom token

### ISSUE THREAD

**Issue by AntonAndell** [balancednetwork/balanced-network-interface#1448]
After a migration to the bnUSD which will happen mid/late september. All bnUSD sent to injective will be instead received in as a denom token. But the CW20 and denom will coexist
This is specific to Injective only for now.
The crossTransfer will work the same but the funds needs to be added along with the call.
To deposit CW20 will stay the same.
Most likely the CW20 will eventually never be used but will be a migration phase.

Denom and CW20 can be sent at the same time as long as funds sent and cw20 balance is enough to cover the amount specified.

**Comment by FezBox** [comment]
@AntonAndell is this ready for the front end to action?

**Comment by swiftcc624** [comment]
Here is the PR - https://github.com/balancednetwork/balanced-network-interface/pull/1509
