### ISSUE TITLE
Supply Liquidity: sICX / bnUSD

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#146]
I don't understand what is happening here. It seems that all transactions are successful, yet the frontend is showing a completely different number for Liquidity Details after completing these transactions. It should show that I have 10,000 sICX and 5,000 bnUSD liquidity supplied.

Sending 10,000 sICX to the DEX:
https://bicon.tracker.solidwallet.io/transaction/0xbe025547c799750d50828bf0522f5d7726cfe115b52f4d61d4c7ec09cc70abd3

Sending 5,000 bnUSD to the DEX:
https://bicon.tracker.solidwallet.io/transaction/0x753757fd523483bf58ed32cb58fa42465718b97bddfa8492332041146fa236bd

Supplying Liquidity:
https://bicon.tracker.solidwallet.io/transaction/0x6efe0ddbc07d059daaff370d0cbef4586e6fdebe0d809894152fc42c507485e0

Frontend Display:
<img width="1025" alt="Screen Shot 2021-04-01 at 12 50 24 AM" src="https://user-images.githubusercontent.com/43685868/113245109-453e9600-9284-11eb-8637-0c33da08a8df.png">

**Comment by BennyOptions** [comment]
Same issue when doing BALN / bnUSD. My starting liquidity was 9.91 BALN and after executing the below transactions it only went up to 9.95 BALN

Send 1,000 BALN
https://bicon.tracker.solidwallet.io/transaction/0x7792d979b65eff4e1d3c7071dc2adf7bef61cae5fa304bf8d7b078d3994a0931

Send 1000.0080696176968 bnUSD
https://bicon.tracker.solidwallet.io/transaction/0xe6c901e57db1399e7b6528a2053add9c0f0c2789962604ef20d02c86e5185c28

Supply
https://bicon.tracker.solidwallet.io/transaction/0x01254f65fa6735b10a3193f1a389f715194dd801e829c4e967b32fc18f2684c9#events

Final display on UI (I started with 9.91 of each)
<img width="1028" alt="Screen Shot 2021-04-01 at 12 59 35 AM" src="https://user-images.githubusercontent.com/43685868/113245745-8daa8380-9285-11eb-806f-eadc0c7191d5.png">

**Comment by tuan-tl** [comment]
Fixed with this PR https://github.com/balancednetwork/balanced-network-interface/pull/161
