### ISSUE TITLE
Supply Liquidity: sICX / ICX

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#148]
Remove the text in the red box. This ICX just stays as ICX. @parrot9design tagging you in case u didn't know.

<img width="426" alt="Screen Shot 2021-04-01 at 1 05 15 AM" src="https://user-images.githubusercontent.com/43685868/113246178-7a4be800-9286-11eb-9a0b-7a84e1e3575e.png">

**Comment by tuan-tl** [comment]
Referencing back here the old issue https://github.com/balancednetwork/balanced-network-interface/issues/141 to continue the discussion

**Comment by BennyOptions** [comment]
Yep, our mistake. Thanks!

**Comment by parrot9design** [comment]
Ah, thanks for catching that! The ICX is still locked though, right? Instead of removing the text, let’s replace it with this:

> Your ICX will be locked in the pool for the first 24 hours.

**Comment by tuan-tl** [comment]
![Screen Shot 2021-04-01 at 14 21 43](https://user-images.githubusercontent.com/48209927/113258021-96d33900-92f5-11eb-99f7-de4e094004fe.png)

Updated with this commit https://github.com/balancednetwork/balanced-network-interface/commit/7594d1c818da671cf733898b4d0b08be3be04c7f
