### ISSUE TITLE
Swap: sICX for ICX Fee Amount is too high

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#153]
This is showing a 10% fee, should be 1%

<img width="431" alt="Screen Shot 2021-04-01 at 1 47 21 AM" src="https://user-images.githubusercontent.com/43685868/113249170-4378d080-928c-11eb-996d-3004505b9e54.png">

**Comment by tuan-tl** [comment]
Fixed with this commit https://github.com/balancednetwork/balanced-network-interface/commit/5b20f0c814f6d1ad9d58d9720590ac2867b04d7c
