### ISSUE TITLE
Implement "Retire Balanced Dollars" modal

### ISSUE THREAD

**Issue by WeiLi512** [balancednetwork/balanced-network-interface#18]
The "Retire Balanced Dollars?" modal appears after clicking the "Return bnUSD" button.

![image](https://user-images.githubusercontent.com/50083174/110891337-c2818580-832c-11eb-921c-650983d025c6.png)

![image](https://user-images.githubusercontent.com/50083174/110891295-b09fe280-832c-11eb-9499-baf38cfaeb21.png)

**Comment by BennyOptions** [comment]
Here is the code

https://github.com/balancednetwork/balanced-frontend/blob/6e97a07b5ba765e1de0c2e61284f495f6d22ab0d/prototype-final/index.html#L151

**Comment by parrot9design** [comment]
> Here is the code
> 
> https://github.com/balancednetwork/balanced-frontend/blob/6e97a07b5ba765e1de0c2e61284f495f6d22ab0d/prototype-final/index.html#L151

That's for the `Withdraw collateral` modal. For the retirement flow code, [see this commit](https://github.com/balancednetwork/balanced-frontend/pull/4/commits/d409e2b85f90766e474e0bfd6b11c399f4023bff)(PR still open).
