### ISSUE TITLE
Improve responsive styles

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#20]
Like [this issue](https://github.com/WeiLi512/balanced-network-interface/issues/19), the layout can be fixed by applying the CSS in full – but particularly the grid layout and responsive styles – as shown in the [Balanced prototype](https://balanced.network/prototype/) and written in the [code](https://github.com/balancednetwork/balanced-frontend/tree/development/prototype-final). 

Examples:

**Current** | **Prototype**
-----------  |  -------------
![Screen Shot 2021-03-13 at 17 54 16](https://user-images.githubusercontent.com/63842577/110894217-5a4a9800-835c-11eb-9303-497f8507b87e.png) | ![Screen Shot 2021-03-13 at 17 54 01](https://user-images.githubusercontent.com/63842577/110894226-5f0f4c00-835c-11eb-9800-2a3e5ba513ee.png)
![Screen Shot 2021-03-13 at 17 54 28](https://user-images.githubusercontent.com/63842577/110894256-6898b400-835c-11eb-8ff0-2c6428e8a955.png) | ![Screen Shot 2021-03-13 at 17 54 48](https://user-images.githubusercontent.com/63842577/110894263-6c2c3b00-835c-11eb-9a18-c264d8976aa8.png)
<img width="419" alt="Screen Shot 2021-03-12 at 6 04 56 PM" src="https://user-images.githubusercontent.com/63842577/110894893-96cac380-835d-11eb-8039-30eefbb8b485.png"> | <img width="406" alt="Screen Shot 2021-03-12 at 6 04 47 PM" src="https://user-images.githubusercontent.com/63842577/110894898-99c5b400-835d-11eb-969b-5f423de3a798.png"><br>Controls should all be left-aligned.
<img width="425" alt="Screen Shot 2021-03-12 at 5 58 10 PM" src="https://user-images.githubusercontent.com/63842577/110895067-ec06d500-835d-11eb-88d7-1336015b05c2.png"> | <img width="412" alt="Screen Shot 2021-03-12 at 5 58 29 PM" src="https://user-images.githubusercontent.com/63842577/110895167-1ce70a00-835e-11eb-9e94-5aa9df239f89.png"><br>We'll hide the Retire flow at mobile initially.

**Comment by WeiLi512** [comment]
For the liquidity details section, Should I remove some columns for mobile?

**Comment by parrot9design** [comment]
Yeah, let's remove the `Pool share` and `Daily rewards` columns at mobile. 👍 

![Screen Shot 2021-03-20 at 10 59 54](https://user-images.githubusercontent.com/63842577/111703265-480fb300-88a2-11eb-84b2-8a9e570c9b24.png)
