### ISSUE TITLE
Add full "Withdraw collateral" modal

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#22]
<img width="500" src="https://user-images.githubusercontent.com/63842577/110896351-46a13080-8360-11eb-8449-c4fbe7f61dbc.jpeg">

[Here's the code.](https://github.com/balancednetwork/balanced-frontend/blob/6e97a07b5ba765e1de0c2e61284f495f6d22ab0d/prototype-final/index.html#L151) Let's get this into the launch release.

**Comment by gedanziger** [comment]
Keep SICX = SICX collateral amount
Wait  = SICX amount -> Convert via SICX price
Swap now = wait * .99
