### ISSUE TITLE
Add other language support to app.balanced.network

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#237]
- Korean
- Chinese
- Dutch
- ??

**Comment by parrot9design** [comment]
I've also had a request for Japanese, and a contact we can leverage for the translation.

@WeiLi512 do you know needs to be done to support multiple languages in the UI?

**Comment by jayenashar** [comment]
most people in the Netherlands can read English so I don't know how much focus it should have

**Comment by jayenashar** [comment]
https://react.i18next.com/ may be useful

**Comment by JPcrypticx** [comment]
Hello 🙂. If it's always in your plans for french, I could be interested to contribute 😊.

We could talk later if you want : Jps_1987

**Comment by BennyOptions** [comment]
This service by Mozilla could be helpful.

https://pontoon.mozilla.org/

**Comment by jayenashar** [comment]
a SaaS service like https://crowdin.com/ might be more cost-effective than running your own pontoon

**Comment by BennyOptions** [comment]
Crowdin is the decision

**Comment by BennyOptions** [comment]
Should be on testnet in one week from now

@parrot9design we need a UI Design on how to switch the language
