### ISSUE TITLE
Fix risk ratio tooltips at mobile

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#327]
If you reduce your browser to the minimum width to simulate a mobile display, the risk ratio tooltips overlap each other, which makes it hard to trigger them on hover at all:

![Screen Shot 2021-04-23 at 5 15 43 PM](https://user-images.githubusercontent.com/63842577/115946768-7b83d400-a517-11eb-9971-4a0e18dde65e.png)

I mocked up a (very) rough design with slightly smaller and more spaced out tooltips:

<img width="442" alt="mockup@2x" src="https://user-images.githubusercontent.com/63842577/115947191-1ed5e880-a51a-11eb-88cd-eacf2abae016.png">

**Comment by BennyOptions** [comment]
Should be done today, we are removing tooltips below a certain size.
