### ISSUE TITLE
Fix the slider and text inputs for the collateral and loan sections

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#330]
If you enter a number into loan input fields, the slider doesn't move to show the correct value, but the position details will update with the correct figures. This has caused an issue where, if you enter a number into the field, you can decrease your risk ratio by increasing your loan.

https://user-images.githubusercontent.com/63842577/115977884-00cabf80-a5d0-11eb-8a40-18588fcc2bcc.mov

It seems to fix itself if you reset it (click Cancel or adjust the collateral), but this is still a major issue because many people will try to use the text fields, and needs to be fixed before launch.

---

Related, if you enter 0 into the collateral deposited field, the slider _does_ move as far as the locked label, but the interface acts as though the collateral balance is 0:

<img width="1055" alt="Screen Shot 2021-04-25 at 2 11 43 PM" src="https://user-images.githubusercontent.com/63842577/115977919-4c7d6900-a5d0-11eb-9145-9cc50ca6cc1e.png">

**Comment by WeiLi512** [comment]
`Related, if you enter 0 into the collateral deposited field, the slider does move as far as the locked label, but the interface acts as though the collateral balance is 0:` @parrot9design Could you guide me on how I have to fix the issue?

**Comment by parrot9design** [comment]
There are two ways we could fix it:

- If a user enters `0` when they have collateral locked, update to the locked value
- Keep the Loan section populated if the loan value is above 0, rather than revert to the empty state text
