### ISSUE TITLE
Refactor Supply Liquidity Flow

### ISSUE THREAD

**Issue by octocat512** [balancednetwork/balanced-network-interface#411]
https://github.com/balancednetwork/balanced-network-interface/pull/403

**Comment by WeiLi512** [comment]
We need to change the fundamental data structures in the front end. So I'd like to refactor the section while working on refactoring the data structures. If we change the fundamental data structure, we would need a lot of work to refactor but we will refactor by section by section.

The reasons:
We need to prepare for routing, and pool count increment. We also have to prepare for pool count increment in UI design part. The current pool selector and token selector UI is not fit for many pools.

![image](https://user-images.githubusercontent.com/50083174/126253139-5fc625d6-dec5-4b4e-aecf-a91991da0a72.png)
![image](https://user-images.githubusercontent.com/50083174/126253167-8398f25a-1486-4067-b362-95989bfd3100.png)

The solutions:
We can leverage the uniswap-sdk-v2 data structure.

**Comment by BennyOptions** [comment]
coupled to #551

**Comment by BennyOptions** [comment]
Done with transaction routing feature
