### ISSUE TITLE
Use these development methods

### ISSUE THREAD

**Issue by octocat512** [balancednetwork/balanced-network-interface#460]
git commit message convention
https://www.conventionalcommits.org/en/v1.0.0/#specification

version control or distribution convention
https://semver.org/

**Comment by avipatel91** [comment]
Thoughts on adding commitizen and hooking it up via husky to create commit message? Commitizen follows Conventional Commit spec.

**Comment by octocat512** [comment]
Thanks for your recommendation. It looks great to me. Let me experience it. Could you help to set up that? So others can experience it.  @avipatel91
