### ISSUE TITLE
Risk Ratio: The bar is not filling properly.

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#49]
It shows that I have reached "All Collateral Locked" but this is not true, I still have bnUSD available to borrow. This should be "Low Risk" I think
<img width="498" alt="Screen Shot 2021-03-25 at 12 23 23 AM" src="https://user-images.githubusercontent.com/43685868/112418692-5cb7d500-8d00-11eb-9013-efb4e3d60f9f.png">
<img width="676" alt="Screen Shot 2021-03-25 at 12 22 49 AM" src="https://user-images.githubusercontent.com/43685868/112418693-5cb7d500-8d00-11eb-9b60-f34aea300562.png">

**Comment by gedanziger** [comment]
Can use existing APIs, implement the formulae for each
