### ISSUE TITLE
Liquidity details: Update values when dragging a withdraw slider

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#498]
When you choose how much liquidity to withdraw from a pool, whether with the slider or input fields, these values in the liquidity details section should adjust to reflect the changes:
- your wallet balance
- your supply
- pool share 
- daily rewards

_Originally mentioned in https://github.com/balancednetwork/balanced-network-interface/issues/445#issuecomment-859333688 and https://github.com/balancednetwork/balanced-network-interface/issues/190_

The bar behind the slider handle should also fill as it's moved across, like they do everywhere else:

![Screen Shot 2021-08-11 at 11 05 15 AM](https://user-images.githubusercontent.com/63842577/128946117-894beaac-bdea-45f7-a724-636232761b4a.png)![Screen Shot 2021-08-11 at 11 07 53 AM](https://user-images.githubusercontent.com/63842577/128946120-cea4dce2-0f05-4f3b-86a4-00658085887e.png)

**Comment by BennyOptions** [comment]
fixed in PR #701
