### ISSUE TITLE
Vote Tab: User Interface for voting on changes to network parameters

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#502]
@parrot9design please share a design for the UX around changing network parameters. Here are some ideas of early things we can let people control:

- "Text" proposal - user submits text and we will vote on making certain changes (i.e. rewarding staked BALN with BALN inflation) - **limit number of characters to 500 maximum (your call)**
- Rewards allocations
- Origination Fee
- Swap Fee
- Fee share between LPs and BALN pool
- Fee share between BALN stakers and DAO fund

**Comment by parrot9design** [comment]
You can view the first version of the Vote page here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype/vote/

The `New proposal` button should be hidden in the first version we push to mainnet, but we've included it here so we can add the ability for users to submit a text proposal on the testnet.

**Comment by BennyOptions** [comment]
"Discussion" will hyperlink to the specific proposal on gov.balanced.network, which is given by the user when submitting a New Proposal

**Comment by parrot9design** [comment]
Yep. We haven't added error handling to the `New proposal` page yet, but if possible, we should check that the link they provide does direct to `gov.balanced.network` instead of an arbitrary URL.

**Comment by BennyOptions** [comment]
Community member finished UI and working on integrating with proposal APIs
