### ISSUE TITLE
Swap tab: Add 25/50/75/100% options

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#519]
This is a feature I would personally like and have had a user request it from me as well. @parrot9design please take care of the design, then mark it as a UI issue and assign to @tuan-tl. Then please share in slack and tag Tuan when it is ready

**Comment by BennyOptions** [comment]
Should also be done by tomorrow

**Comment by parrot9design** [comment]
You can check out the design for this here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/

The options will only be displayed when you click one of the input fields, and the wallet balance of the first asset will no longer be clickable.
