### ISSUE TITLE
UI/UX around listing a new pool

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#539]
Other platforms allow you to list your own pool directly from the UI rather than needing to be a developer. See screenshot from Uniswap below.

<img width="946" alt="Screen Shot 2021-07-06 at 5 00 04 PM" src="https://user-images.githubusercontent.com/43685868/124666204-b2615900-de7b-11eb-8ca8-101cff552076.png">

<img width="494" alt="Screen Shot 2021-07-06 at 5 01 15 PM" src="https://user-images.githubusercontent.com/43685868/124666267-cc02a080-de7b-11eb-992f-05cd5734a712.png">

**Comment by parrot9design** [comment]
You can preview the custom LP design here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/#

## Searching for assets/pools
Related: #264, #763
![Screen Shot 2021-11-10 at 2 30 28 PM](https://user-images.githubusercontent.com/63842577/141033911-75090d28-ce46-4457-ac89-ad8942f8a218.png) ![Screen Shot 2021-11-10 at 2 30 55 PM](https://user-images.githubusercontent.com/63842577/141033916-9482c311-a038-4cc0-8850-1189c6c412ed.png) 

You should be able to search by asset name, ticker, or contract address. If there are no results for your search, you should see this message:


![Screen Shot 2021-11-15 at 2 24 45 PM](https://user-images.githubusercontent.com/63842577/141708301-6a7f2af2-28dd-429e-8584-409d3332cc2a.png) ![Screen Shot 2021-11-15 at 2 26 33 PM](https://user-images.githubusercontent.com/63842577/141708303-3ea70c76-09b0-4f8a-ab94-0fa659244e51.png)


For the Swap list, we should also adjust the order logic:
- Order assets from highest to lowest based on the amount you hold
- Every 0-balanced asset should then be listed in alphabetical order


## Create a new pool

There's an `Add new pool` button at the end of the supply dropdown, which becomes more apparent when you search.
![Screen Shot 2021-11-10 at 2 32 15 PM](https://user-images.githubusercontent.com/63842577/141034219-75eea0d4-0e9c-409e-83ff-c6896998bfb0.png)

Click it to bring up this modal:

![Screen Shot 2021-11-11 at 6 24 00 PM](https://user-images.githubusercontent.com/63842577/141242332-687a4e26-492a-445b-8985-cb0178a9c20c.png)

Enter a contract address into the top-left field. We're assuming the front-end will be able to detect the currency automatically, but we can adjust this if that's not the case.

Click the right-side asset to bring up the asset dropdown (logic not included in the design), which should show 4 assets: 
- bnUSD
- IUSDC
- sICX
- USDS

When both assets have been chosen, we should check to make sure that pool doesn't already exist. If it does, display this message:

![Screen Shot 2021-11-15 at 2 28 45 PM](https://user-images.githubusercontent.com/63842577/141708504-54fd86b1-735a-43b8-9c63-7c66f0760987.png)

Clicking in either of the Amount fields should bring up the % options:

![Screen Shot 2021-11-15 at 2 16 21 PM](https://user-images.githubusercontent.com/63842577/141707722-057d74bb-7f8b-4403-81d0-63e8a005e381.png)


When an amount has been entered for both assets, update the price conversions:

![Screen Shot 2021-11-11 at 6 22 30 PM](https://user-images.githubusercontent.com/63842577/141242355-409bdd91-e3e8-4ea0-8232-8d54cd393254.png)

When satisfied, click `Create pool`, then either create the pool and supply liquidity (if possible in 1 tx – this is what we should be aiming for), or direct them to the existing supply liquidity flow to deposit their assets into the smart contract.


### Banner messages:

> Creating Asset1 / Asset2 pool...

> Asset1 / Asset2 pool created. _x_ Asset1 and _y_ Asset2 supplied.

> Couldn't create Asset1 / Asset2 pool.


---

That should about cover it, but we can provide more design guidance around error handling and anything else we may have missed, if necessary.

**Comment by octocat512** [comment]
The frontend doesn't show the confirmation modal for creating a new pool? @parrot9design

**Comment by octocat512** [comment]
I think that the frontend needs to have the UI for adding new custom token. @parrot9design

**Comment by parrot9design** [comment]
We’ve updated the modal to include a `Deposit` button for each asset:

![65919D9C-8AD9-4D05-9B56-527982105AFC](https://user-images.githubusercontent.com/63842577/143837788-afc8f0fb-0175-4c9c-b895-2e6f26d6d062.jpeg)

Banner messages:

> Sending _x asset_ to the Balanced exchange.

> _x asset_ sent to the Balanced exchange.

After you deposit an asset, the button should change to `Withdraw`:

![737C513A-86B0-4031-BDAF-EAEAF413FE73](https://user-images.githubusercontent.com/63842577/143837874-4a8500c0-c541-439c-90af-1466a826bc9e.jpeg)

After both assets have been deposited, the `Create pool` button will become active.
