### ISSUE TITLE
Transaction Routing UI

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#551]
Create a UI to display transaction routing

First step
<img width="488" alt="Screen Shot 2021-07-12 at 10 01 10 PM" src="https://user-images.githubusercontent.com/43685868/125393371-b221fb80-e35c-11eb-811d-a5f6394ca188.png">

Tooltip
<img width="500" alt="Screen Shot 2021-07-12 at 10 01 39 PM" src="https://user-images.githubusercontent.com/43685868/125393443-d2ea5100-e35c-11eb-80c6-bfaa8b44912c.png">

**Comment by BennyOptions** [comment]
Will start working on it this week, research done, should finish this week

**Comment by BennyOptions** [comment]
hoping to finish on testnet this week

**Comment by lijac** [comment]
@gedanziger  would you let me know the addresses of the routing contract? mainnet and testnet, please

**Comment by BennyOptions** [comment]
Main features are working now, working out small bugs.

@gedanziger please share the testnet address of the Router contract so they can test

**Comment by gedanziger** [comment]
```
{"loans": "cxf932e077b96652e73bb3fc230152afd98a38e41a", "router": "cxd440e80b77f46bdea5ea3ab1f90c62f9d3cf8821", "staking": "cx3f792d3dad2c6bd5344c9ed264f01a7d99eb28ab", "dividends": "cxdfa57910a86bc086d1ceb5143940fe11f39a85dc", "reserve": "cx37678c01be2a1343c9e45c8727fd41f90ff4b9fe", "daofund": "cx818cd9ae4c3c2cffe4c618e8381668c44fb3a1a8", "rewards": "cx3980f745a70cf450e042c1c7123ed56d901d8dea", "dex": "cx435324e61249b94cc803ab3c4cf6860b83834d73", "governance": "cxb42e1aa8954b6d58b34e3d05575cc810070b42c7", "oracle": "cx61a36e5d10412e03c907a507d1e8c6c3856d9964", "sicx": "cx6166d1a0a945ebe166cf040dfe079c3679a2243e", "bnUSD": "cxe8ce82b9c62aab559ebb508f7976d5282187ecce", "bnXLM": "cxde1fb6a4eda5b0792ccb42fd5ccc79f7de968085", "bnDOGE": "cx5a0a9718775aafc573f0188bd6252288463fcea0", "baln": "cxed80524a8071583e0498bae0e95712b093c733a8", "bwt": "cx200a7d6e5a381d82b1d84f0bde7dcf609db9f3ac"}
```

yeoiodo addresses

**Comment by BennyOptions** [comment]
Issue should be finished this week to ship to production

**Comment by BennyOptions** [comment]
Use this to test @parrot9design 

https://balanced-network-interface-6ist619dy-balanced-dao.vercel.app/

**Comment by BennyOptions** [comment]
blocked by ICON 2 for now
