### ISSUE TITLE
Alternative Collateral Types UX

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#564]
We need a design around using different collateral types. My suggestion is quite simple actually. I'd like to add a ":" next to "Collateral" along with a drop-down menu to select different collateral types.

From there, the Position Details, Loan and Collateral tabs would represent only for that specific collateral type/position.

Rewards and wallet would not be changed.

**Comment by BennyOptions** [comment]
Should have it done by tomorrow

**Comment by parrot9design** [comment]
http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/

There's no logic in place yet, but when you click an asset, it should:

- load your current position (if any)
- show the current price of the asset in the position details section
- change the ticker for `Collateral sold` in the rebalancing section

It's not responsive right now, but we'll get that in place within the next day or so.

**Comment by parrot9design** [comment]
@hetfly we’ve modified the dropdown design to include more details about each collateral position:

![22F258BA-0D6C-4BED-AAE6-1140F0749584](https://user-images.githubusercontent.com/63842577/143835278-4adc1bc7-62ed-4b49-a023-d58a02d70be6.jpeg)

You can play around with it here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/
