### ISSUE TITLE
Transaction History Bug: Unstaking sICX

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#576]
When unstaking sICX, transaction history shows the amount of ICX waiting to be received, not the amount of sICX unstaked. In this screenshot below, transaction history should show 614.48 sICX, not 629.93. 629.93 is the amount of ICX about to be received, not the amount unstaked.

Transaction: https://tracker.icon.foundation/transaction/0xc08721f943a5be9d648ff7c6d06d5dcaaeff06955424ba670179425af11153bd

![history bug.jpg](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/052d8085-ea5d-4b75-ae44-a240a0f0e919)

**Comment by BennyOptions** [comment]
Change the number for both "Activity" and "Amount" column to match the sICX amount

**Comment by hieunguyenebox** [comment]
the api will update to return the correct value

**Comment by BennyOptions** [comment]
There is an issue now with how it is labeled

![Screen Shot 2021-08-09 at 7.40.12 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/75296e88-6899-4d06-b821-417aa55f3169)
