### ISSUE TITLE
Remove the reward threshold from the risk ratio

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#578]
In preparation for a vote to remove the reward threshold, we need to reconsider the risk ratio section. The reward threshold defined the design of this section, as it helps users optimise their rewards and manage their risk more closely. Because of it, only a small number of positions were liquidated when the market turned.

[On the forum](https://gov.balanced.network/t/lower-collateral-requirements-remove-rewards-threshold/29/), some have already voiced concern about how well they and others will manage their risk after we remove the reward threshold indicator, especially if we also lower collateral requirements. 

It may be a simple fix, like changing the label from `Reward threshold` to `Safety threshold`, but should be considered carefully from a design perspective before we submit this proposal to the community.

Related: https://github.com/balancednetwork/balanced-contracts/issues/288

**Comment by parrot9design** [comment]
Okay, let’s go with the approach shown in this prototype variation: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/

Key points:
- Remove the reward threshold
- Move the `All collateral locked` indicator to 81.79%, to represent 35% LTV or a collateral ratio of 285%*
- Update the logic for collateral/loan to allow the ability to borrow up to 35% of the collateral value


*If you’re wondering about the math, the main section of the risk bar starts at a collateral ratio of 900%, ends at 150% (the liquidation rate).

Let’s get this ready to go for when [the 35% LTV vote](https://app.balanced.network/vote/proposal/2) ends and the changes executed in a few days.

**Comment by dbrehmer** [comment]
I edited the percentages since the threshold will actually be set to 285.71% - 
1 - (285.71 - 150)/ (900 - 150) = .819053333 => 81.905%

Hmm, it might look a little scary with a lot of open space between low risk and the threshold. Maybe the bar should be shaded with a gradient to indicate increasing risk?

**Comment by parrot9design** [comment]
Thanks @dbrehmer! It felt a bit empty and uncertain to us, as well, so for now, we’ve decided to adapt the reward threshold instead of removing it completely (details in previous comment). We can then see if people still rely on it to manage their position, and if not, phase it out to a more minimal, gradient-style approach.

**Comment by parrot9design** [comment]
Hmm, somehow I managed to delete the previous comment. 

@WeiLi512 here’s how the risk ratio should operate now: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/

Key changes:
- Change `Reward threshold` to `Safety threshold` and change the tooltip content to `You’re more vulnerable to price movements if you go beyond this threshold.` 
- Move the `All collateral locked` indicator to 81.905% along the bar to allow for up to 35% LTV / 285.71% collateral ratio*
- Make sure the collateral/loan logic are updated to allow for 35% LTV

*For reference, the main bar shows a collateral ratio of 900% - 150%.
