### ISSUE TITLE
Add loading animations to the Vote page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#586]
When the Vote page and Proposal pages load in information, it's a bit jerky, and may take a moment. Let's add a placeholder design, and make the pages animate more smoothly.

This is the framework @WeiLi512 suggested for the placeholder animation: https://material-ui.com/components/skeleton/

Based on that, and the design of the vote page ([testnet](#559), [prototype](http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/vote/proposal/)), we could use variants like this:

First section:
- H2 variant 
- Text
- Text or rectangle

Description:
- H2 variant
- Rectangle

The React knowledge required for this means it'll be difficult for us to provide the design for. @hetfly Do you want to have a crack at this and see what you can come up with?

**Comment by hetfly** [comment]
@parrot9design  sure, happy to!
