### ISSUE TITLE
Fix minor issues for vote pages.

### ISSUE THREAD

**Issue by WeiLi512** [balancednetwork/balanced-network-interface#588]
- [x] fix issues mentioned in this comment. https://github.com/balancednetwork/balanced-network-interface/pull/559#issuecomment-892183493
- [x] fix gap issue on safari. css gap is not working on safari.
- [x] We don't have voters count data for the first vote. so show `- voters` if there is no data.  
![image](https://user-images.githubusercontent.com/50083174/128117889-d2926f81-2ceb-4ed4-9df6-63bdb5db1305.png)

**Comment by WeiLi512** [comment]
safari 14.1 adds support for flex gap

**Comment by seeyijie** [comment]
14.0.2 does not support CSS gap

**Comment by gitdiff75** [comment]
Safari 14.0.2 does not support flex gap

**Comment by gitdiff75** [comment]
Fixed them all except for the error message for failed transaction which should be handled by the contracts:
https://github.com/balancednetwork/balanced-contracts/search?q=Balanced+tokens+need+to+be+staked
