### ISSUE TITLE
Vote Tab: Discussion and Transaction Links on first proposal

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#589]
These links do not work for me, please do the following:

Red = vote transaction on tracker.icon.foundation

Yellow = remove text or remove hyperlink styling, there is no discussion

![Screen Shot 2021-08-03 at 9.36.39 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/e32bf708-47aa-4213-a197-8a1be8928153)

**Comment by WeiLi512** [comment]
@dbrehmer said that it is difficult to return the vote creation transaction hash for now. I'd like to remove it now.
