### ISSUE TITLE
Fix issues on the Vote page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#595]
There are a few more issues that need fixed on the Vote/Proposal pages.

![Screen Shot 2021-08-06 at 7 15 38 AM](https://user-images.githubusercontent.com/63842577/128408938-12f4c90d-4f4a-45c8-b66c-fa9830533769.png)

- [x] - The % voted should be the amount of eligible BALN that has already voted (with 20% being the minimum required). There's no way it's already at 99.99%. We should also cap the number to 2 decimal places.
- [x] - There's a weird visual issue at the start of the Approve and Reject bars.
- [x] - Approve needs to include `(67% required)` if it's not being taken care of in [this PR](https://github.com/balancednetwork/balanced-network-interface/pull/591).
- [ ] - We need to add links to the [discussion](https://gov.balanced.network/t/bip2-increase-ltv-to-35/139/3) and blockchain transaction.

----

Also mentioned by Dan in Slack:

> The community reported that the displayed voting weight does not include the BALN in the pools. I checked as I just voted and it shows just the staked BALN in the initial pop up, but then shows the correct full weight in the result. 

> Also, the 100% voted is not correct. It should be the sum of the for and against from the data returned by checkVote. Those are given as a percent of total voting power. For the Approve and Reject percentages they have been correctly converted to a percent of votes cast, but for the % voted number the sum can be used directly.

**Comment by parrot9design** [comment]
The checkVote method from which the data come is here - https://github.com/balancednetwork/balanced-contracts/blob/development/core_contracts/governance/governance.py#L264. See the definition of _for and _against on lines 277 and 278.

**Comment by WeiLi512** [comment]
For now, we don't have any solutions to automatically get discussion URLs and transactions hashes.
So we need to do that manually now. @parrot9design @parrot9design

**Comment by parrot9design** [comment]
Yes, it will have to be manual until we can automate it on the front end. Are you able to manually add them to the UI for this proposal?

**Comment by WeiLi512** [comment]
I can add discussion url and transaction hash.

**Comment by WeiLi512** [comment]
The transaction hash is the hash of creating a proposal?
