### ISSUE TITLE
BalancedDAO voting page on mobile MyIconWallet not working.

### ISSUE THREAD

**Issue by Sugertukas** [balancednetwork/balanced-network-interface#600]
BalancedDAO voting page on mobile MyIconWallet not working. Using Android, Samsung Galaxy S9.
Attached video file.

https://user-images.githubusercontent.com/88653686/128678698-559b020c-c4ff-456b-953a-d73b533c725b.mp4

**Comment by WeiLi512** [comment]
Please hard refresh the app. Please let me know if the voting page is still not working.

**Comment by BennyOptions** [comment]
Another related issue @WeiLi512, let me know if you think this should be a separate issue

Address: hxf915fdaadce5508559495cd3244b0136a127ca3a

Video is in zip file below

[mobile wallet issue.mp4.zip](https://github.com/balancednetwork/balanced-network-interface/files/6956557/mobile.wallet.issue.mp4.zip)

**Comment by Sugertukas** [comment]
Tried to clear app cash, myiconwallet app up to date. Still not working.
