### ISSUE TITLE
Claimable ICX from unstaking sICX: UI Indication

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#603]
Let's somehow indicate in the UI that a user has available ICX to claim without them needing to click "ICX" in the "Wallet" tab. Been having a few users come into chat asking about where their unstaked ICX is.

**Comment by parrot9design** [comment]
Yea this is my bad, I have know for a while that there has been a lack of affordance with the wallet section. In our earlier mock-ups we actually had affordance for each item (with labels like “Send” and “Menu”) but I hated the redundant repetition:
![BALANCE](https://user-images.githubusercontent.com/63842577/129815432-4ec457b1-1a71-45e4-8fcd-1a7a4ee48abf.png)
In hind-sight the obvious solution would of been to just go with a down facing chevron:
![BALANCE](https://user-images.githubusercontent.com/63842577/129815452-8d0eaa07-2900-4e64-968f-345e89e3885c.png)
As for the notification side of things, I think we can substitute out the down facing chevron for a green dot when there is something that the user needs to pay attention to. This is a standard convention across the web:
![Screen Shot 2021-08-18 at 11 40 24 AM](https://user-images.githubusercontent.com/63842577/129815484-836f1cdf-240a-4cce-a782-fb7adb96ba53.png)
![Support](https://user-images.githubusercontent.com/63842577/129815492-3005aff7-d274-481b-aabb-d7e1235fa9ed.png)
Which means it would look something like this in Balanced:
![BALANCE](https://user-images.githubusercontent.com/63842577/129815512-bfc7ac54-ac35-466f-a594-5dce0be2692a.png)
![BALANCE](https://user-images.githubusercontent.com/63842577/129815531-159ae0a2-f42c-4eb6-88a8-de94887b465d.png)

**Comment by WeiLi512** [comment]
![image](https://user-images.githubusercontent.com/50083174/129998329-9565a882-6390-45b6-9c5c-447423377a15.png)
I don't have any unstaking ICX. Is it right to show the indicator in that situation? @parrot9design
