### ISSUE TITLE
Trade page: Make BALN/bnUSD the default chart

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#604]
Whenever you go to the Trade page, you're greeted with the chart you care the least about: sICX / ICX. It's quite boring, given that the price increases linearly over time, and you can't do anything with it (line only, can't change time periods). 

BALN is the most important asset on Balanced, and most people (including ourselves) check the price of that first, so we should default to the BALN / bnUSD chart instead.

**Comment by WeiLi512** [comment]
@tuan-tl, I'd like to assign the task to one dev who works on the trial task. Because he has to refactor the trade page. I'd like to let him be familiar with the trade page while doing this issue.
