### ISSUE TITLE
Transaction Notifications: Lower the time

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#606]
Let's lower the amount of time it takes for the confirmed transaction notification to disappear. I'm thinking we cut it in half. @parrot9design thoughts?

**Comment by parrot9design** [comment]
Yeah, it's much longer than it needs to be. 5 seconds should be plenty. 👍

**Comment by BennyOptions** [comment]
Ok, let's go with 5 seconds.
