### ISSUE TITLE
Vote Page: Include LPed BALN in voting weight

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#610]
Currently, the BALN in LP does not appear in the confirmation modal for voting

**Comment by WeiLi512** [comment]
https://github.com/balancednetwork/balanced-contracts/pull/311

**Comment by BennyOptions** [comment]
Blocked by SCORE - must be live on main net

**Comment by BennyOptions** [comment]
Currently works on testnet
