### ISSUE TITLE
Update the proposal metadata

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#611]
We should always include the amount of hours remaining in a vote. With a voting window of 5 days, each "day left" is worth 20% of the total, so`3 days, 13 hours left` is more useful than `4 days left`.
![Screen Shot 2021-08-14 at 15 16 43](https://user-images.githubusercontent.com/63842577/129432623-fc9758f7-af4d-4b57-92bc-4e7267dcb6b2.png)

Let's replace the `Executed` term with `Enacted`. It has the same meaning, but is more neutral/less gruesome. 😅
![Screen Shot 2021-08-14 at 15 17 22](https://user-images.githubusercontent.com/63842577/129432637-b020c6b9-8e31-4d0a-93b5-d43c78725364.png)

**Comment by parrot9design** [comment]
Approved proposals should say `Approved`, not `Approve`.

![Screen Shot 2021-08-18 at 8 48 35 AM](https://user-images.githubusercontent.com/63842577/129798463-2cf523d0-d732-46df-897e-53338b6ad533.png)

**Comment by BennyOptions** [comment]
There is also an issue reported by users that the time changes/displays incorrectly
