### ISSUE TITLE
Wallet Tab: Scaling with more tokens added to Balanced

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#617]
How will we adjust the wallet as more tokens are available to trade and supply as collateral?

In theory, we could remove the wallet tab, but just an option.

**Comment by BennyOptions** [comment]
@WeiLi512 also suggested going the other direction, making an entire wallet tab. We will still think about this

**Comment by BennyOptions** [comment]
Any thoughts on this @parrot9design? I'm leaning toward only displaying Balanced-specific assets, ICX, BALN and bnUSD. Definitely leaning away from having a full wallet or wallet tab

**Comment by WeiLi512** [comment]
https://github.com/balancednetwork/balanced-network-interface/issues/644
