### ISSUE TITLE
Wallet Tab: Change the ICX Unstaking Display

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#62]
Let's only have 1 aggregate unstaking amount.

@parrot9design - please make a new design

<img width="490" alt="Screen Shot 2021-03-25 at 5 53 02 PM" src="https://user-images.githubusercontent.com/43685868/112548699-0182f280-8d93-11eb-9d1b-17c9520f162f.png">

**Comment by parrot9design** [comment]
<img width="431" alt="Screen Shot 2021-03-28 at 5 00 59 PM" src="https://user-images.githubusercontent.com/63842577/112742031-646cc780-8fe7-11eb-9acd-2c9ffdebbb17.png">

```
<div class="grid-cell">
	<h3>Unstaking</h3>

	<p class="label">Your ICX will be unstaked as more collateral is deposited into Balanced.</p>

	<dl class="metadata">
		
		<dd>9,716 ICX unstaking</dd>
	</dl>
</div>
```
