### ISSUE TITLE
Wallet Tab: Text boxes don't work and "Send Max" does not work either

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#63]
It is not possible to type in either the wallet address or the amount. When you click "Send Max" it takes you to the top of the page. This applies to all assets, not just ICX

<img width="492" alt="Screen Shot 2021-03-25 at 5 56 40 PM" src="https://user-images.githubusercontent.com/43685868/112548985-78b88680-8d93-11eb-9b4f-211faacf78df.png">

**Comment by gedanziger** [comment]
This issue is for the UI. Send should be integrated to the API.
