### ISSUE TITLE
Listing: IUSDC : bnUSD

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#630]
Let's list both of these pools and merge the PR when OMM launches

**Comment by parrot9design** [comment]
Let's make sure to remove the row for rewards, as well.
![Screen Shot 2021-08-24 at 4 28 13 PM](https://user-images.githubusercontent.com/63842577/130555861-304fd15e-e1eb-4d95-9ca1-4dc5c626971f.png)
