### ISSUE TITLE
Vote Page: Add "New Proposal" Button & Proposal Types

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#632]
Add the new proposal button with the following options for a user:

https://docs.google.com/spreadsheets/d/1W__eUg8pS2_iQi5cEzZMzFg2rUMl11Q2vfjujhZkQUY/edit#gid=1178561104

**Comment by parrot9design** [comment]
@BennyOptions will all of these be adjustable by the community in the first release? We'll need to finalise the UI to allow for submissions that aren't text-only.

**Comment by parrot9design** [comment]
@tuan-tl, all the proposal types and the confirmation modal are now here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/vote/new-proposal/


A few notes…

Use these banner messages after completing the transaction:
- Submitting proposal…
- [proposal type] proposal submitted. (i.e. `Text proposal submitted.`, `BALN allocation proposal submitted.`)

—

Use these messages for any form validation errors:

Forum link: `Must link to a discussion on gov.balanced.network.`
Allocations: `Allocation must equal 100%.`
Collateral ratio: `Must be less than the liquidation threshold (67%).`

We can display them using the same style as in this issue: https://github.com/balancednetwork/balanced-network-interface/pull/503

We should only display them after the user tries to submit the proposal, unless you can find a way to handle it inline smoothly (the BALN allocation inputs, especially). For the allocation error, display it next to the final row.

If there are any other errors we’ll need to surface to users, let me know and I’ll provide wording for them.

—

This assumes that the default start time for each proposal will be the next daily snapshot (10am Pacific / 5pm UTC). We could add the ability to schedule the start date, depending on how we decide to schedule proposals in general ([forum thread](https://gov.balanced.network/t/standardized-voting-days/230)), but that doesn’t need to be in place for v1.

—

For each proposal, we should automatically display the forum and transaction links so it’s easy for voters to find more info about a particular change. At the moment this is a manual process that hasn’t been in place until near the end of a vote, if at all.

—

We’ve assumed the 100 bnUSD requirement is all that matters here. @BennyOptions, wasn’t there also a requirement for them to hold a certain amount of the total BALN, like 0.1% or something?

**Comment by BennyOptions** [comment]
All transactions go to the governance contract and call the defineVote method

How to call the defineVote method: https://github.com/balancednetwork/balanced-contracts/pull/303/files#diff-0092b0bb773d0bdb0060fe99c5ee88f2fb8e56db7adb3299cfec0fc80162f826R159

def defineVote(self, name: str, description: str, vote_start: int, 
                   snapshot: int, actions: str = "{}") -> None:
- Name: "title" in the UI
- description: "description" in the UI
- vote_start: getDay + 1 (getDay is from the loans contract)
- snapshot: getDay
- actions: Dictionary
 Keys - method names
 values - dictionaries of parameters for each action

Example for BALN Allocations:
https://github.com/balancednetwork/balanced-contracts/blob/development/core_contracts/governance/data_objects.py#L29

RECIPIENTS = [{'recipient_name': 'Loans', 'dist_percent': 15 * 10**16},
              {'recipient_name': 'sICX/ICX', 'dist_percent': 7 * 10**16},
              {'recipient_name': 'sICX/bnUSD', 'dist_percent': 175 * 10**15},
              {'recipient_name': 'BALN/bnUSD', 'dist_percent': 175 * 10**15},
              {'recipient_name': 'IUSDC/bnUSD', 'dist_percent': 5 * 10**15},
              {'recipient_name': 'Worker Tokens', 'dist_percent': 20 * 10**16},
              {'recipient_name': 'Reserve Fund', 'dist_percent': 25 * 10**15},
              {'recipient_name': 'DAOfund', 'dist_percent': 20 * 10**16}]

actions = json.dumps({"addNewDataSource": {"_data_source_name": "IUSDC/bnUSD"}, "updateDistPercent": {"_recipient_list": RECIPIENTS}})

**All keys will be method names**


Network Fee Allocation:
UI Validation: Must equal 100%

Getters for current stats: testnet cx203d9cd2a669be67177e997b8948ce2c35caffae
- DAO Fund: getDividendsPercentage (returns both)
- BALN Holders: getDividendsPercentage (returns both)

Setters: cx203d9cd2a669be67177e997b8948ce2c35caffae testnet
https://github.com/balancednetwork/balanced-contracts/blob/development/core_contracts/dividends/utils/consts.py#L7
- setDividendsCategoryPercentage
BALN_HOLDERS = "baln_holders"
DAOFUND = "daofund"

Loan Fee: testnet contract cx3259f3ff9a51ca3bf170d4ff9104cf4af126ca1c (loans contract)
- UI Validation: 10% maximum, only 2 decimal points
- Multiply user input by 100
- Example: User enters 2.15 -> submit 215 to the blockchain

getter: getParameters

Collateral Ratio:
- getter: 1,000,000 / (getParameters from Loans contract (locking_ratio) / 10,000
- User input: 1,000,000 / input and round to an interger
- Input validation:  no higher than 80

**Comment by BennyOptions** [comment]
Change "Collateral Ratio" to "Loan to Value" in the UI @tuan-tl

**Comment by parrot9design** [comment]
Just make sure it’s sentence case. 😄

> Loan to value ratio

**Comment by BennyOptions** [comment]
Merged with previous upgrade
