### ISSUE TITLE
Position Details: Rebalancing Section doesn't change between day/week/month

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#64]
When selecting an option from the drop-down, it does not work

<img width="275" alt="Screen Shot 2021-03-25 at 6 04 34 PM" src="https://user-images.githubusercontent.com/43685868/112549742-a651ff80-8d94-11eb-99c2-446e4b148c9c.png">

**Comment by gedanziger** [comment]
@tuan-tl to check if it's implemented in the backend, then update

**Comment by gedanziger** [comment]
This issue is not for implementing the backend endpoint and API integration, this is just updating it to say "Past Week", "Past Day", ... in the UI when clicked.
