### ISSUE TITLE
Wallet Tab: IUSDC Price does not show

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#644]
Change this to be $1 per IUSDC (use the same policy of bnUSD)

![Screen Shot 2021-08-25 at 7.45.25 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/c410c03a-0fdd-41b4-a9ac-cecd0e9b5920)

**Comment by octocat512** [comment]
Add USDS price data.
