### ISSUE TITLE
White screen for some users

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#646]
When users login and are on the "Home" tab, the app breaks and the screen turns white. It seems all users are based in Turkey, but it could be a coincidence.

Addresses effected:
hxeeaa8bda8d9a2c895ee5874af91c59be0c8ce22e
hx5ee4f0e5bcd3a671cd439806210ea8b3b81f7059 - Iconex
hx22c18e20e3ef29ebecb86e4680e12d8f609d78d8 - MyIconWallet mobile app 
hx00a61ff047f5e3a5ec9dc9dd0ba001168381bc6b - MyIconWallet mobile app
 hxd7f7a9b8c4882caa1303ead43936c6292958fada - MIW

**Comment by BennyOptions** [comment]
https://images.zenhubusercontent.com/322745209/f7cba4bd-a756-48fe-a15f-00af6ff6c3be/issue.mp4

**Comment by octocat512** [comment]
This issue is solved. The day.js package caused the issue.

**Comment by octocat512** [comment]
For now, I'd like to close the issue.

**Comment by BennyOptions** [comment]
Did we fix the issue for Turkey and New Zealand?
