### ISSUE TITLE
Wallet Tab: SCORE API for Unstaking amount from sICX management contract 

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#65]
Please integrate the SCORE API after issue #62 is complete.

@dbrehmer please provide the SCORE API and SCORE address for total unstaking request for a given address as a comment here

**Comment by dbrehmer** [comment]
You can get info on unstaking from the readonly method
staking.getUserUnstakeInfo(_address) -> list
The list will be 
[unstaking_amount, sender_address, unstaking_block_height, sender_address]
This may change since it does not make sense to have the sender_address in there twice.

**Comment by tuan-tl** [comment]
Added getUserUnstakeInfo as of here https://github.com/balancednetwork/balanced-network-interface/pull/84
