### ISSUE TITLE
Position Details: Change "ICX" to "sICX", remove rounding

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#662]
Please remove the logic to convert data from sICX into ICX and change the UI to say "sICX". Also, there might be a rounding issue as well. Please look into it

hex value in red box: 0x45c1241470b7a710e9

![rounding.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/db82784d-48e0-4b97-a41c-db3076690c56)

![Screen Shot 2021-09-11 at 7.16.02 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/46df3afc-b7f8-44ca-aa96-e0db7419100d)

**Comment by octocat512** [comment]
While doing that, I'd like to change the collateral unit to sICX on the homepage. @BennyOptions @parrot9design

**Comment by parrot9design** [comment]
No, we’ll be adjusting this later to use both sICX and ICX, but not now.

**Comment by badbusiness** [comment]
Haven't been able to reproduce the rounding error from master. 

Also, the ICX value comes straight from api. need to read up, but haven't found a way to get sICX value from api. I don't think it can be converted on the frontend because ICX <> sICX value changes over time.
