### ISSUE TITLE
OSX: scrollbar for tokens and liquidity

### ISSUE THREAD

**Issue by aatomik1** [balancednetwork/balanced-network-interface#666]
Tokens and Supply Liquidity should have a visible scroll bar when opening those menus.
Looks like OSX issue only, scroll bar is visible on Windows systems.

On Mac it will show a black scroll bar once you move mouse over it and start scrolling. Same with Brave and Chrome.

**Comment by BennyOptions** [comment]
Will likely be addressed in the new UI with a search bar
