### ISSUE TITLE
Migrate test.balanced.network to Sejong

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#670]
We need to test on Sejong testnet going forward.

@dbrehmer @gedanziger please share the contract addresses both here and on slack

**Comment by BennyOptions** [comment]
"loans": "cx3228124be7c85e3e57edebf870c4075c33c34c5f",
    "staking": "cx1eb5b209e4c6f95a958bddb322d76a2168e576b2",
    "dividends": "cx020042bb8742bfca138889e23817bee87ad8caa0",
    "reserve": "cx76d98fc79f779308d2e872b00e7571bebef59031",
    "daofund": "cx11781737f47520e3bfad0e132c5accb4e4d6fe4f",
    "rewards": "cx026ca90fdcf4851fa6c4e00403b3abe636a9f88b",
    "dex": "cx4342802efce67d2441e69b062b1f0110b6a6f820",
    "rebalancing": "cxd5df399205421930870e3b0798766aa31cffbe66",
    "governance": "cxdc519895ef110220db2442ff1b3223182304b68a",
    "oracle": "cxf96a2e83808058fb9159824e324f36d9e91cfafa",
    "sicx": "cx0e706eca3552a6e607095319f4ad8cea37e779d4",
    "bnUSD": "cx041714d034919c8456d3606f8766f0169e35cb8e",
    "bnXLM": "cxcc80a99118e2e35db8e9a575f86d87e33c2a9465",
    "bnDOGE": "cx47f5be000e9893936e415b1b704001dd43467889",
    "baln": "cxb45058d398614a7c8cdf7be6f556fa0b39399799",
    "bwt": "cxa2afb37647ae91ca6fbf35141b2ef2ac7105720a"

**Comment by BennyOptions** [comment]
@dbrehmer please comment on this issue when the Sejong contracts are ready

**Comment by ajaya-man** [comment]
Is it still blocked due to price oracle issue @octocat512 ?
