### ISSUE TITLE
Displaying implied ICX price

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#675]
As sICX becomes more and more valuable, I think it's important for us to display the ICX price as well. I was thinking we could do it in _italics_ where I've highlighted in red, but this is becoming an issue in the community as people think sICX is way overpriced when it's actually only a few percent.

![Screen Shot 2021-09-14 at 1.20.14 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/5dc799da-f0d8-4fa5-b22a-aa24ff16a062)

**Comment by BennyOptions** [comment]
should have design done tomorrow

**Comment by parrot9design** [comment]
For all sICX pairs, let's add a second line with the ICX conversion. It should use the `label` styles (`font-size: 14px;` `color: rgba(255,255,255,0.75);`):

![Screen Shot 2021-09-22 at 2.30.41 PM.png](https://images.zenhubusercontent.com/5f07ce93b980486c01f6f1f8/3186a1ee-7d25-4b23-9a46-394bb75433c8) ![Screen Shot 2021-09-22 at 2.32.13 PM.png](https://images.zenhubusercontent.com/5f07ce93b980486c01f6f1f8/dfb00050-5a9b-4f11-8ff6-88cd7e3f589d)

**Comment by BennyOptions** [comment]
Overall, the goal is to display users easy to understand price data in ICX terms. sICX price confuses users, so we need to fix this issue somehow
