### ISSUE TITLE
View & manage your collateral in both ICX and sICX

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#686]
We’ve updated the design of the Collateral section to allow users to display the values in ICX or sICX – just like you can on Omm. This is necessary for several reasons:

- The current design is optimised for new users, who hold ICX, but not for existing users, who are more likely to hold sICX.
- There's endless confusion about the interaction between ICX/sICX, especially where staking rewards come into play.
- When you withdraw collateral, it's not added to the Collateral > Wallet balance (because it's sICX, not ICX), which has also caused some confusion.
- sICX holders can deposit from the wallet, but they can't preview how the added collateral will affect their position until after the transaction has taken effect. That means advanced users – who care more about the details  – get a second-rate experience.
- When we support multiple collateral types, it no longer makes sense to allow sICX collateral to be deposited from the wallet. Each collateral type is a separate position, so if you had ETH active, it wouldn't make sense to be able to deposit sICX from the wallet, as it would affect a position the user has no context of in that moment.
- If sICX can be deposited as collateral from the wallet section, why not every other collateral type, as well? It becomes difficult to scale.

---

The new design includes a footer with the ability to swap between the ICX and sICX values, as well as a tooltip to explain the interaction.

<img width="492" alt="empty-state" src="https://user-images.githubusercontent.com/63842577/133871422-58fc950c-2acd-4809-a176-917e8fa58d32.png">

The ICX/sICX Deposited value is the same. The Wallet value is the amount of that asset the user has available in their wallet. 

Interaction details:
- If someone has no collateral, default to the ICX view, as this provides the best onboarding experience. If they already hold sICX, they'll know what to do.
- After collateral has been deposited, default to the sICX view.
- If possible, adjust the Rebalancing value in the position details section to display in ICX or sICX terms, depending on which currency is active.

When a user confirms changes to their collateral, display a variant of the Deposit/Withdraw modal, depending on the active currency:

**ICX** | **sICX**
------- | ---------
![deposit-icx](https://user-images.githubusercontent.com/63842577/133871475-33d9debb-e09a-4689-bd1a-5996407c27b3.png)<br>Your ICX will be converted to sICX (Staked ICX).<br><br>You’ll receive sICX when you withdraw, which you can unstake or swap for ICX on the Trade page. | <img width="404" alt="deposit-sicx" src="https://user-images.githubusercontent.com/63842577/133871481-6fdb3bdf-0f59-44ef-aa30-959b8c6a08f8.png">
<img width="417" alt="Screenshot 2021-09-17 at 7 51 13 PM" src="https://user-images.githubusercontent.com/63842577/133871601-5a834711-f44e-4a58-a4f1-c4aea7ea74f1.png"><br>You’ll receive sICX (Staked ICX). Unstake it from your wallet, or swap it for ICX on the Trade page.  | <img width="403" alt="withdraw-sicx" src="https://user-images.githubusercontent.com/63842577/133871495-1304dc86-a155-4fa9-b24b-9a5777a9e431.png">

 As part of this update, we can also remove `Deposit` from the sICX wallet entry.

You can view the footer design here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/
Not that it usually is, but note that this code shouldn’t be copied exactly – the footer has been positioned absolutely (so it isn’t responsive) and the collateral dropdown is being handled in another issue. 

Any questions, let us know. 😊

**Comment by parrot9design** [comment]
Hey @hetfly now that you've finished the performance details, do you want to tackle this one?

**Comment by hetfly** [comment]
For sure

**Comment by BennyOptions** [comment]
Should be done this week

**Comment by BennyOptions** [comment]
blocked, waiting for refactor of Home tab
