### ISSUE TITLE
Sometimes, colors don't appear in the OMM and USDS logos.

### ISSUE THREAD

**Issue by octocat512** [balancednetwork/balanced-network-interface#699]
One thing I noticed on iOS, is that the colors sometimes don't appear in the OMM and USDS logos, and there's still an issue where the BALN circle isn't visible. Any idea what's causing that to happen?
https://github.com/balancednetwork/balanced-network-interface/pull/684#issuecomment-921325042

**Comment by octocat512** [comment]
SVG image gradients attributes are conflicts. so it makes the issue. and it will make more issues in the future as we add more tokens.
So I suggest using the png file format for the token logos.
https://github.com/trustwallet/assets
I think the repo will be a standard repo for all token information. So I hope to follow their standard in terms of the logo format. And I'd like to add the balanced tokens to the repo. Want to request our tokens to their trust wallet in the future.
@parrot9design @BennyOptions

**Comment by parrot9design** [comment]
Shared the png files in the above issue, so closing this one now.
