### ISSUE TITLE
Add lock feature to slider

### ISSUE THREAD

**Issue by WeiLi512** [balancednetwork/balanced-network-interface#7]
Add the lock sticker to limit moving the slider thumb.

![image](https://user-images.githubusercontent.com/50083174/110724055-0b174100-8250-11eb-94ea-69b0379e99fa.png)

**Comment by parrot9design** [comment]
There's also a similar one for the Loan section:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/63842577/110747262-fadc8180-82a2-11eb-9463-98a06bff5f46.png">

This one appears if the user doesn't have enough bnUSD in their wallet to repay the full loan, at the point where their bnUSD wallet balance = 0.

**Comment by gedanziger** [comment]
Complete, bugs will be opened as separate issues
