### ISSUE TITLE
Implement Deposit SICX Collateral API

### ISSUE THREAD

**Issue by gedanziger** [balancednetwork/balanced-network-interface#70]
In #66, there is a feature for depositing sICX to the loans contract (instead of depositing just ICX). Implement this so it can be called from the frontend:

![image](https://user-images.githubusercontent.com/5342263/112569403-56c60080-8da1-11eb-88f1-390eef0d5c15.png)

- contract: sicx
- method: transfer
Example Params:
```
{'_to': contracts['loans']['SCORE'], '_value': 200 * ICX, '_data': json.dumps({"method": "_deposit_and_borrow", "params": {"_sender": wallet.get_address(), "_asset": "", "_amount": 0}}).encode()}}
```

**Comment by tuan-tl** [comment]
Updated with this PR
https://github.com/balancednetwork/balanced-network-interface/pull/83
