### ISSUE TITLE
Staking LP tokens UI/UX

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#701]
Sorry @parrot9design but we realized we need to do this to migrate to continuous rewards. If we don't do it, we can't have a modular architecture for adding new incentivized pools.

**Comment by parrot9design** [comment]
You can preview the LP token staking design (without logic) here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/

The new design will no longer include a column for the `Withdraw` option – instead, all pools will be expandable:

![Screen Shot 2021-10-31 at 3 22 04 PM](https://user-images.githubusercontent.com/63842577/139564158-726e05ea-0d6e-40d2-9735-dc6147d4dacb.png)


There are 3 variations based on the pool type...

### sICX / ICX
![Screen Shot 2021-10-31 at 3 21 26 PM](https://user-images.githubusercontent.com/63842577/139564162-0e272f42-1914-4119-bf19-47963310c62a.png)

### Pools that don't receive BALN
![Screen Shot 2021-10-31 at 3 23 59 PM](https://user-images.githubusercontent.com/63842577/139564204-08e75178-60ad-4022-bace-32494c480b3e.png)

- Should display the amount of LP tokens their liquidity equates to, and hint that they could earn more for them elsewhere (prevents us needing to manage links/reward info for different projects).
- The `Wallet` balance usually shown in the Withdraw modal is now `Available`, and should indicate the amount of liquidity available to withdraw. It should start decreasing towards 0 as the slider is dragged.
- The design shows a BALN value in the Daily Rewards column, but it should be a `–` instead.

### BALN-incentivised pools
![Screen Shot 2021-10-31 at 3 25 30 PM](https://user-images.githubusercontent.com/63842577/139564214-19d3d2f3-8df1-436a-a986-219e04b08408.png)

- Slider should work the same as in the Collateral and Loan sections: when you click `Adjust`, the slider appears along with the `Cancel` and `Confirm` buttons.
- As you move the slider, the `Daily rewards` and `Available` values should also change (Available = unstaked supply balance)

### Modals
![Screen Shot 2021-10-31 at 15 34 10](https://user-images.githubusercontent.com/63842577/139564411-3f1889bf-5805-4063-9417-f1b9a6c8cfb3.png) ![Screen Shot 2021-10-31 at 15 34 18](https://user-images.githubusercontent.com/63842577/139564412-1729dbf9-0f4e-4823-8cb4-435f1026ebb1.png)

```
<div id="modal-stake-lp-tokens" class="modal modal-show">
			<div class="modal-content">
				<!-- Overview -->
				<h3 class="label text-center">Stake LP tokens?</h3>
				<p class="text-bold text-center">250</p>

				<!-- Comparison -->
				<div class="grid comparison">
					<div class="grid-cell text-center border-right">
						<p class="label">Before</p>
						<p>0</p>
					</div>

					<div class="grid-cell text-center">
						<p class="label">After</p>
						<p>250</p>
					</div>
				</div>

				<p class="label text-center">You'll earn BALN until you unstake them.</p>

				<!-- Modal actions -->
				<div class="modal-actions">
					<a href="#" class="cancel modal-close">Cancel</a> <a href="./" class="button">Stake</a>
				</div>
			</div>
		</div>
```

```
<div id="modal-unstake-lp-tokens" class="modal modal-show">
			<div class="modal-content">
				<!-- Overview -->
				<h3 class="label text-center">Unstake LP tokens?</h3>
				<p class="text-bold text-center">250</p>

				<!-- Comparison -->
				<div class="grid comparison">
					<div class="grid-cell text-center border-right">
						<p class="label">Before</p>
						<p>250</p>
					</div>

					<div class="grid-cell text-center">
						<p class="label">After</p>
						<p>0</p>
					</div>
				</div>

				<p class="label text-center">You'll stop earning BALN from them.</p>

				<!-- Modal actions -->
				<div class="modal-actions">
					<a href="#" class="cancel modal-close">Cancel</a> <a href="./" class="button">Unstake</a>
				</div>
			</div>
		</div>
```

### Supply liquidity section

Let's remove the content shown for incentivised pools:
![Screen Shot 2021-10-31 at 3 39 06 PM](https://user-images.githubusercontent.com/63842577/139564544-5b45e2e8-602d-4529-a6da-b764965a722e.png)![Screen Shot 2021-10-31 at 3 39 18 PM](https://user-images.githubusercontent.com/63842577/139564548-9f21e274-0e51-4c36-b1a0-f24f15e82d08.png)

So instead they look like this:
![Screen Shot 2021-10-31 at 3 39 31 PM](https://user-images.githubusercontent.com/63842577/139564554-1385d612-834b-40ed-9b14-857ebf769fe2.png)

We may add a tooltip for some/all of the pools instead, but for now let's just cut the content as it won't be correct with continuous rewards.

**Comment by BennyOptions** [comment]
Make sure to include the logic on #498

**Comment by BennyOptions** [comment]
Note - make sure to remove custom OMM content as we are moving away from maintaining this and being responsible for the dependency

**Comment by BennyOptions** [comment]
Waiting for "add custom pair" and smart contract deployments
