### ISSUE TITLE
Rebalancing section not displaying reverse rebalancing

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#710]
ICX amount should be a positive number and loan amount should be positive. Both are 0.

Here is an address that should display positive numbers for both under "past day"

hx2d5504331f7e11d91d3a394538ce64a12f8dbf5f

**Comment by pranav925** [comment]
https://balanced.geometry.io/api/v1/stats/rebalanced?address=hx2d5504331f7e11d91d3a394538ce64a12f8dbf5f&token_symbol=bnUSD&from_timestamp=1633071252000000

The resync fixed the issue

**Comment by BennyOptions** [comment]
fixed - was a backend issue
