### ISSUE TITLE
Implement bnUSD price on rebalance notifications

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#723]
Use the geometry backend API to get the bnUSD price into the notification after rebalancing occurs

**Comment by parrot9design** [comment]
This would be the complete message:

>Rebalancing complete. 1 bnUSD = $x.xxxx.

i.e.

>Rebalancing complete. 1 bnUSD = $0.9817.

[Mentioned here](https://github.com/balancednetwork/balanced-network-interface/pull/722#issuecomment-940612529)
