### ISSUE TITLE
Wallet Tab: Implement the ability to send ICX, send tokens, stake BALN, and unstake sICX

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#75]
Currently, this is just a UI. It needs the API integration to actually send transactions.

For unstaking sICX, this is waiting on issue #74 

<img width="485" alt="Screen Shot 2021-03-26 at 12 24 38 AM" src="https://user-images.githubusercontent.com/43685868/112576945-b6d09d00-8dc9-11eb-8625-4d00c2466743.png">

**Comment by tuan-tl** [comment]
Updated with these PRs:

- https://github.com/balancednetwork/balanced-network-interface/pull/96
