### ISSUE TITLE
Change format of vote actions string to a list

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-network-interface#752]
The actions parameter in the defineVote method on the governance SCORE has been changed from a json strong of a dictionary to a json string of a list. With the actions as keys of a dictionary they could only be invoked once. This will allow a method to be invoked more than once.

The vote definition method is here - https://github.com/balancednetwork/balanced-contracts/blob/development/core_contracts/governance/governance.py#L167

The actions parameter is now a json string of the form
```
[['<action_1>', {<kwargs for action_1>}],
['<action_2>', {<kwargs_for_action_2>}], [..]]
```

**Comment by BennyOptions** [comment]
Waiting on a contract deployment

**Comment by BennyOptions** [comment]
@dbrehmer can you confirm that we still need to make this change, and if so, is the contract prepared for it?

**Comment by dbrehmer** [comment]
This is complete already. I'm not sure how it is still open. I have not been seeing it in the ZenHub task list.
