### ISSUE TITLE
The time formatting for BALN unstaking is wrong 

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#757]
Please fix the time formatting for BALN unstaking periods. 10:6am is incorrect. I assume it should be 10:06am.

![CleanShot_2021-10-29_at_08.12.172x.jpg](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/a33dca38-2f79-47a3-a43b-e60a0f352ef7)

**Comment by octocat512** [comment]
You want the 2-digits format for minutes.
What digits format do you want for hours?
https://day.js.org/docs/en/display/format
![image.png](https://images.zenhubusercontent.com/60ee2a5c8011c1b3416184ab/1fa9f1ce-b849-402d-b502-0fcfa9be7091)

**Comment by BennyOptions** [comment]
01-12 is the decision @octocat512
