### ISSUE TITLE
Position details: Add more information about rebalancing

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#759]
There's been a lot of confusion and concern about rebalancing, so we can begin to address that by making it clearer in the UI.

### Rebalancing modal
If it's someone's first time borrowing, this message should appear after they click `Confirm`, before they see the confirmation modal:
![Screen Shot 2021-10-31 at 15 48 07](https://user-images.githubusercontent.com/63842577/139564758-cba31c28-579f-4d81-8d5e-82a945f6b303.png)

```
<div id="modal-rebalancing" class="modal modal-show">
	<div class="modal-content">
		<!-- Overview -->
		<h3 class="label text-center">Rebalancing</h3>

		<p style="font-size: 16px;">While you borrow bnUSD, your collateral is used to keep its value stable</p>

		<div class="grid graphical-options">
			<div class="grid-cell">
				<img src="../img/icon/rebalancing-below.svg">
				<p class="text-bold">If bnUSD is below $1</p>
				<p class="label">Balanced sells collateral at a premium to repay some of your loan.</p>
			</div>
			<div class="grid-cell">
				<img src="../img/icon/rebalancing-above.svg">
				<p class="text-bold">If bnUSD is above $1</p>
				<p class="label">Balanced increases your loan to buy more collateral at a discount.</p>
			</div>
		</div>

		<p class="label">You'll receive BALN as a reward, and can mitigate the fluctuations by supplying liquidity to the sICX/bnUSD pool. The smaller your loan, the less rebalancing affects you.</p>

		<!-- Modal actions -->
		<div class="modal-actions">
			<a href="./" class="button">Understood</a>
		</div>
	</div>
</div>
```

### Rebalancing tooltip

We should present the information from the modal in the Rebalancing tooltip, so it's accessible to people at all times. We've included a secondary tooltip, which shows the average price based on the rebalancing values, and the % higher/lower it is from the current ICX price.

![Screen Shot 2021-10-31 at 3 52 34 PM](https://user-images.githubusercontent.com/63842577/139564998-e816a917-cba0-4e73-97cf-085eadd2f228.png)

Top tooltip content is the same as in the modal. Bottom tooltip content:

>Your average rebalancing price was **$x.xxxx**.

### Position details tweaks

In addition to the rebalancing tooltip, we moved `Liquidated` outside of the risk ratio bar & added the price next to it, so we could then display the current bnUSD price underneath the ICX price.

You can preview the design here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/

**Comment by BennyOptions** [comment]
Overall looks good, just a couple suggestions:

1.) Replace "keep the price stable" with "keep its value stable". Imo, "the price" is a little unclear as to what the collateral is being used for.

2.) Would like to remove "which is x% higher/lower than the current price" because I think it encourages people to mint more bnUSD to repurchase from the DEX and/or highlights situations when it has not been favorable, which will happen

3.) Something seems off about the infographics - like they are not aligned with each other, but can't put my finger on it.

4.) Replace "you'll receive BALN as compensation" with "you'll receive BALN as a reward". Phrasing it as compensation is riskier to @parrot9design imo, but your call

**Comment by hetfly** [comment]
Finishing up, not sure how to get information about first borrowing ever. The modal now displays if user has $0 loan and tries to borrow. Is this ok or do we want to use local storage not to show the modal in cases where user already had a loan, repaid it and tries to borrow again ?
