### ISSUE TITLE
Banner for critical network changes/votes/upgrades

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#762]
Let's create a banner that can be easily changed and turned on/off

- Changes to LTV
- Network outages
- Critical bugs
- etc.

**Comment by parrot9design** [comment]
You can find the banner design here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/

The text is just placeholder for now. We can provide the wording when we have something specific to notify people about.

**Comment by parrot9design** [comment]
The continuous rewards upgrade seems like the perfect time to crack out the banner message, wouldn't you agree @BennyOptions? Thinking something like this:

<img width="1009" alt="Screen Shot 2021-12-09 at 5 52 55 PM" src="https://user-images.githubusercontent.com/63842577/145336683-bf72648b-2c3a-413c-a456-109d0539dcac.png">


```
<div class="banner">
	<div class="grid grid-center">
		<div class="grid-cell">
			<p class="label">Balanced now distributes Balance Tokens as you earn them, instead of once every 24 hours. <span class="text-bold text-white">Liquidity providers won't earn BALN</span> until they stake 'LP tokens' from the liquidity details section. <a href="https://blog.balanced.network/november-2021/#continuous-rewards">Learn more about the continuous rewards upgrade.</a></p>
		</div>
		<div class="grid-cell text-right close">
			<a href="#">
				<img src="../img/icon/cross.svg">
			</a>
		</div>
	</div>
</div>
```

**Comment by Chunn** [comment]
@parrot9design Could you help me confirm how to show the banner in  http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/? I can not find it.
@BennyOptions Could you help me clarify banner behavior?
Where will it be implemented? 
 Thank you!

**Comment by parrot9design** [comment]
> @parrot9design Could you help me confirm how to show the banner in http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/? I can not find it. @BennyOptions Could you help me clarify banner behavior? Where will it be implemented? Thank you!

If you go to the page and inspect element, you'll see this line near the top:

<img width="557" alt="Screen Shot 2022-02-15 at 6 12 22 PM" src="https://user-images.githubusercontent.com/63842577/153996843-c6b00bb8-2687-4b50-9985-13f549da8a5d.png">
Remove the `hide` class to view it.

Regarding where it will be implemented, let's put it at the top of each page until it's dismissed.

**Comment by Chunn** [comment]
@parrot9design Thanks for sharing! 🙇‍♀️

**Comment by parrot9design** [comment]
No API needed for this content. It’s just a manual string change, so we’ll have to provide new content every time we need to show a banner in the UI. For continuous rewards, we just need the content in [this comment](https://github.com/balancednetwork/balanced-network-interface/issues/762#issuecomment-989511230). Thanks!
