### ISSUE TITLE
The Funding logic doesn't consider the token decimals in the Vote page.

### ISSUE THREAD

**Issue by octocat512** [balancednetwork/balanced-network-interface#769]
If a voter uses IUSDT or USDC as a funding source, then it won't work. Please check the sections.
https://github.com/balancednetwork/balanced-network-interface/blob/59c7cf0432a0153b95267dcf2c2a4515c5976923/src/app/containers/ProposalPage/Funding.tsx#L28

https://github.com/balancednetwork/balanced-network-interface/blob/59c7cf0432a0153b95267dcf2c2a4515c5976923/src/app/containers/NewProposalPage/constant.ts#L212

- please remove the eslint lint comments in the `FundingInput` component while fixing the issue. 
- I'd like refactor the code using new data structures by branching from tx routing PR.

**Comment by BennyOptions** [comment]
We will only use bnUSD, BALN and sICX as funding mechanisms, so it is ok
