### ISSUE TITLE
Reposition the banner notification messages at smaller screen sizes

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#771]
When you confirm a transaction on mobile, the notifications appear at the bottom. They shouldn't. 

<img width="400" src="https://user-images.githubusercontent.com/63842577/141719305-8bce338f-1425-444f-a5d3-e57ba3331d33.PNG"> <img width="400" src="https://user-images.githubusercontent.com/63842577/141719396-5dfee1b8-8a71-4bf8-8f76-b347c8bbe13e.PNG">

<img width="400" src="https://user-images.githubusercontent.com/63842577/141719401-a0cc1712-600a-42a8-bcf9-b013b360ac11.PNG"> <img width="400" src="https://user-images.githubusercontent.com/63842577/141719405-7e594d55-15c6-4d63-be83-1b7c3a8a125a.PNG">

Having them at the bottom prevents people from being able to use the navigation or complete the supply liquidity flow, as they first have to get rid of the messages. We should display them at the top of the screen instead, where they're not in the way.

**Comment by hetfly** [comment]
Notification will show top center on screens < 1000px
