### ISSUE TITLE
Use the CurrencyAmount data structure for the wallet redux store. 

### ISSUE THREAD

**Issue by octocat512** [balancednetwork/balanced-network-interface#774]
For now, the frontend uses BigNumber for the wallet redux store. This `BigNumber` is not fit the storing wallet's token balance info. Please check the logic here. https://github.com/balancednetwork/balanced-network-interface/blob/59c7cf0432a0153b95267dcf2c2a4515c5976923/src/store/wallet/reducer.ts#L10

After the tx routing PR, we have the `CurrencyAmount` data structure for balance info. Please use the `CurrencyAmount` instead of `BigNumber`. Also, use the address key instead of the symbol key. 

This data structure change will require a lot of code changes in the overall codebase. So please refactor the below items in sequence.

- [x] use the refactored hook `useCurrencyBalances` to fetch wallet balances in the `useWalletFetchBalances` hook. https://github.com/balancednetwork/balanced-network-interface/issues/772
- [x] refactor `WalletPanel`
- [x] refactor `SendPanel`
- [x] refactor `Unstake Panel` in sICX and ICX wallet
- [x] refactor `DepositPanel`
- [ ] refactor `CollateralPanel` and `LoanPanel`

**Comment by octocat512** [comment]
Expected Results:
We should ensure code consistency for future development after the tx routing PR. We're applying improved code to WalletPanel, SendPanel, UnstakePanel, DepositPanel, CollateralPanel, LoanPanel.

**Comment by BennyOptions** [comment]
Blocked by #772
