### ISSUE TITLE
Vote time remaining

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#784]
There are 23 hours left, but it shows "Active". It should say "23 hours remaining". 

![Screen Shot 2021-11-18 at 1.12.17 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/cdba4b18-da9b-4196-baa1-53e7fc292577)

**Comment by rise-techiast** [comment]
From 24 hours to 23 hours -> time point that triggered active status

**Comment by hetfly** [comment]
```bnJs.Governance.getDay()```
is returning 305 when it should return 306 IMO
when is platform day counter increased?

**Comment by BennyOptions** [comment]
12:23 pm PST on Feb 28th, vote finishes 9am PST on March 1st, UI says "Active", it should say "~21 hours remaining"

@hetfly 

![Screen Shot 2022-02-28 at 12.22.57 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/50044e47-0f3d-4804-a2b8-24c5df772752)

**Comment by BennyOptions** [comment]
Platform day counter is increased everyday at 9am PST

**Comment by hetfly** [comment]
Waiting on mainnet proposal to test and finish up
