### ISSUE TITLE
Typing in "for" section always results in failed transaction

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#796]
The minimum to receive param does not update properly when typing in the "For" section of the swap. It always sets minimum to receive as the exact amount in the "For" section. All user trades will revert if they type in the "For" section

Transaction: https://tracker.icon.foundation/transaction/0xd613048bea30259a6030acf9144e0a9cff8c2a402425d779eb6e8a3be4f273f7

![min to receive.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/6e333547-d3dc-40f7-8e29-fd8d86ceeeef)

**Comment by BennyOptions** [comment]
This issue still exists when swapping from sICX to ICX.

https://images.zenhubusercontent.com/322745209/c35236a1-0c6b-437f-a476-438aa1426a92/screen_recording_2021_12_01_at_5_51_46_pm.mov

**Comment by lijac** [comment]
That was the intended behavior. The transaction goes through, right?
For direct queue pair transactions, slippage has no effect.

**Comment by BennyOptions** [comment]
Hey @lijac - actually, the transactions are still failing. If a user types into the "For" section, and the "For" token is ICX, the transaction always fails. Here is are some examples:

https://tracker.icon.foundation/transaction/0x9755e03f30347f54a42b9e2ff2314b4c1e3cb5bd5ce549bfe0cd7e2c99eaff9e
https://tracker.icon.foundation/transaction/0xb77a60009ce7a77d8cd745eb8309445209d5d795b3f4e0d90b0b2cbbec77a8d8


https://user-images.githubusercontent.com/43685868/144514132-4293234b-07d3-454a-91d2-f668585b760b.mp4
