### ISSUE TITLE
Wallet values don't update properly

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#797]
The pricing in the "wallet" panel is not accurate anymore. I had a few users report this, and I checked as well.

![Screen Shot 2021-11-22 at 2.25.36 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/c5039d90-5bcd-44d2-8702-cc423425fe00)

**Comment by octocat512** [comment]
The current ICX price in the position details section came from the band oracle price.
The ICX price in the wallet section came from our backend price API that is used in the stats web app.
@BennyOptions

**Comment by octocat512** [comment]
I think that @pranav925 has to find the reason for the difference. @BennyOptions @pranav925

**Comment by BennyOptions** [comment]
This issue is fixed because the price worker is fixed. It was a backend issue.
