### ISSUE TITLE
Implement risk ratio slider correctly in the Risk Ratio section as in the prototype.

### ISSUE THREAD

**Issue by WeiLi512** [balancednetwork/balanced-network-interface#8]
Please reference the prototype. https://balanced.network/prototype/

- [ ] implement risk ratio slider as in the prototype
- [x] add tooltips as in the prototype

![image](https://user-images.githubusercontent.com/50083174/110724801-6e55a300-8251-11eb-941f-8fb14c105391.png)

**Comment by parrot9design** [comment]
Also for this section:

* [ ] Left-align `Loan`
* [ ] Give the borrowLimit value the `label` style (`/ $2,587` in the current version)

**Current** | **Prototype**
-----------  |  -------------
<img width="125" alt="Screen Shot 2021-03-11 at 6 56 59 PM" src="https://user-images.githubusercontent.com/63842577/110742765-caddb000-829b-11eb-88f9-330dd66f0e28.png"> | <img width="138" alt="Screen Shot 2021-03-11 at 6 57 11 PM" src="https://user-images.githubusercontent.com/63842577/110742768-cd400a00-829b-11eb-9e49-737d1fc11644.png">

**Comment by gedanziger** [comment]
closing this as a duplicate
