### ISSUE TITLE
Decimal Precision Swap Panel

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#804]
Please fix the decimal precision, it is too precise. We can keep 4 decimal places maximum.

![Screen Shot 2021-11-24 at 1.33.34 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/c645c1a9-927d-4178-bf2c-5f5aa2be8a09)

**Comment by sonicsmith** [comment]
Added PR for this here: https://github.com/balancednetwork/balanced-network-interface/pull/811

Change to using `toFixed(4)` instead of `toSignificant()` for both "Wallet" displays on this Tab only.
