### ISSUE TITLE
Change Eligibility logic for Network Fees

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#829]
LPs do not earn network fees anymore. Now, eligibility logic is only staked BALN.

This should be merged into the continuous rewards branch (LP token staking)

**Comment by BennyOptions** [comment]
Change the below to: "Stake BALN tokens to be eligible for network fees"

![Screen Shot 2021-12-26 at 5.59.02 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/9667aca0-1bdb-444a-94d9-d6db955dc6ec)

**Comment by BennyOptions** [comment]
New logic:

If user has Staked BALN **and** no unclaimed rewards:

"Pending"

If user has no Staked BALN:

"Ineligible"
![Screen Shot 2021-12-26 at 5.58.43 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/a2d9fdc5-533a-476c-b1c9-26cb5774b14a)

**Comment by octocat512** [comment]
duplicated #820
