### ISSUE TITLE
Minimum to receive not working properly

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#830]
The frontend did not properly pass the Minimum to Receive number to the blockchain.

![issue.PNG](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/2ee42714-d010-43a1-bc2a-5b453e91330b)
![thing.PNG](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/03b35365-d1d3-4d68-9650-06ed402cf314)

Transaction:
https://tracker.icon.foundation/transaction/0x5a6b07b3c5fa3613627f5e65ae10aaccdff2f8aa72e5e8c8784ebaa6475c17a0

**Comment by lijac** [comment]
https://sejong.tracker.solidwallet.io/transaction/0x5c6e6d895f74220f16abad78e9534d8d544a812b0b88564d90032037d62e62c7
