### ISSUE TITLE
Design: Fix dropdown arrows on Supply Liquidity tab

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#836]
It would be good to align all arrows in the drop down menus regardless of the number of characters for the asset.

<img width="366" alt="Screen Shot 2022-01-06 at 2 28 37 AM" src="https://user-images.githubusercontent.com/43685868/148345641-3106eee7-84e1-4af7-a111-c8afea6cc965.png">

**Comment by avipatel91** [comment]
I can take this one up.
