### ISSUE TITLE
Trade Routing Calculation Fix

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#857]
**Manual trade:**
IUSDC > OMM > sICX > ICX = 3013 ICX

**UI Calculated Trade Route:**
IUSDC > bnUSD > sICX > ICX = 2992 ICX

Manual trade is better

![photo_2022-01-20_23-22-56.jpg](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/203e11f0-d13a-41f1-86ca-7c04ccbdc43d)

**Comment by octocat512** [comment]
@lijac please take a look.
