### ISSUE TITLE
Trade Router Issue

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#858]
This trade should never have been created by the frontend, we must understand why/

Somebody made an sICX/IUSDC with a bad price. Pool ID 36. The frontend never should have selected it for the IUSDC -> sICX trade, as a better route was available

https://tracker.icon.foundation/transaction/0x475360286c044974e4c7b1ff1b363dd31413efb4913d05e13870c2009d00b7b7

**Comment by lijac** [comment]
@BennyOptions Can we close this?
