### ISSUE TITLE
Remove the 24 hour lock from the liquidity pool content

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#86]
**sICX/ICX**
> Earn Balance Tokens every day you supply liquidity. Your assets will be locked for the first 24 hours, and your supply ratio will fluctuate with the price.

**BALN/bnUSD**
> Earn Balance Tokens every day you supply liquidity, and start accruing dividends. Your supply ratio will fluctuate with the price. 

**sICX/bnUSD**
> Earn Balance Tokens every day you supply liquidity. Your supply ratio will fluctuate with the price. 

<img width="632" alt="Screen Shot 2021-03-28 at 1 33 10 PM" src="https://user-images.githubusercontent.com/63842577/112738698-3cbb3680-8fca-11eb-81cb-5074b0693a9a.png">

**Comment by tuan-tl** [comment]
Updated with this PR https://github.com/balancednetwork/balanced-network-interface/pull/93
