### ISSUE TITLE
Update the UI for BIPs 17, 18, and 20

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#860]
We need to update the Home page logic to support the changes proposed in:

https://app.balanced.network/vote/proposal/24
https://app.balanced.network/vote/proposal/25
https://app.balanced.network/vote/proposal/27

The LTV will be updated to 66.67%, and the liquidation ratio to 85%.

- Collateral `Locked` indicator should max out at 66.67% LTV 
- Loan `Available` should allow for up to 66.67% of collateral value

Position details:
- `All collateral locked` should represent 66.67% LTV
- `Liquidation` should represent 85% LTV

Related: https://github.com/balancednetwork/balanced-network-interface/issues/861

**Comment by octocat512** [comment]
The UI used the blockchain API to fetch Lock LTV and Liquidation LTV. We don't need to care about the LTV proposals change in the future. @BennyOptions @parrot9design
