### ISSUE TITLE
Adjust the price chart time frames on the Trade page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#863]
The 4H and 1D time frames aren't sufficent for traders who want to assess price action on a larger scale. Let's replace the `5m` option with `1W` to provide a weekly perspective:

![Screen Shot 2022-01-24 at 5 22 42 PM](https://user-images.githubusercontent.com/63842577/150721687-93fc6410-f8dd-41e2-a708-2e003f452d5f.png)

**Comment by shallcdn** [comment]
This issue need to BE enhance the API

**Comment by parrot9design** [comment]
The weekly option has been added, but let's remove the `5m` option before we close this issue.
