### ISSUE TITLE
Update the risk ratio bar

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#865]
We shouldn't imply that a position of any size is "low risk". 

Let's remove that label and its tooltip, and merge it with the larger bar. You'll need to take care to optimise for smaller positions, as the logic of the low risk section is slightly differt to make sure a value is displayed on the bar for all position sizes.

<img width="643" alt="Screen Shot 2022-01-25 at 5 02 09 PM" src="https://user-images.githubusercontent.com/63842577/150909194-c0df9811-2356-473d-84ad-03b8a28c4647.png">

**Comment by octocat512** [comment]
@parrot9design In my knowledge, the risk ratio bar is 1/LTV ratio bar. What about making LTV ratio bar?

**Comment by parrot9design** [comment]
> @parrot9design In my knowledge, the risk ratio bar is 1/LTV ratio bar. What about making LTV ratio bar?

If the LTV and liquidation rate aren't likely to change, we could absolutely switch to an LTV ratio bar that scales from 1- 100. It didn't make sense to scale it like that before, because with the borrow limit at 25% and liquidations at 67%, a large chunk of the bar would be unusable. That's less of an issue with these numbers.

It would also resolve this glitch I noticed on the new bar:

https://user-images.githubusercontent.com/63842577/151281862-829eb860-39be-4f8c-94be-de781a183eb4.mov



(I had to do it fast to trigger it, but you can tell where the separation used to be.)

**Comment by hetfly** [comment]
@parrot9design removed the animation, the separation is still visible if you trying really fast, otherwise seems ok
