### ISSUE TITLE
IUSDC decimals on mobile UI

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#868]
Decimals are off

![USDC bad decimals on mobile.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/73590bab-a42e-44c4-ae23-7fe1e4d79eda)

**Comment by octocat512** [comment]
@BennyOptions Can you reproduce the bug in the current production build?

**Comment by hetfly** [comment]
@BennyOptions it seems ok now, can you confirm?
