### ISSUE TITLE
Vote Tab: Can't sign transaction

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#873]
When submitting a "Text Proposal", a transaction is never created. I am never prompted on Ledger nor on ICONex/Hana to sign the transaction. 

![Screen Shot 2022-02-01 at 12.56.36 AM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/2c908a08-fe57-4aae-82c2-2c57a20c6fc6)

**Comment by octocat512** [comment]
I fixed the bug in [this PR](https://github.com/balancednetwork/balanced-network-interface/pull/878). @BennyOptions
