### ISSUE TITLE
Display a proposal's Approve/Reject bars when signed out

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#888]
At the moment, you can't see the current Approve/Reject status of a vote unless you're signed in while viewing the proposal...

<img width="1054" alt="Screen Shot 2022-02-13 at 9 11 52 AM" src="https://user-images.githubusercontent.com/63842577/153727478-35f5b037-58df-4068-8fa8-116ce232cbbe.png"><img width="1057" alt="Screen Shot 2022-02-13 at 9 11 43 AM" src="https://user-images.githubusercontent.com/63842577/153727473-71ca2657-58fd-4eaa-8414-f553995efbcb.png">

...Or rely on the data from the main Vote page:
<img width="977" alt="Screen Shot 2022-02-13 at 9 35 41 AM" src="https://user-images.githubusercontent.com/63842577/153727534-3af878c0-0754-443a-8d8c-d4d500753a93.png">

We should always show the Approve/Reject bars, whether you're signed in or not:

<img width="1050" alt="Screen Shot 2022-02-13 at 9 37 04 AM" src="https://user-images.githubusercontent.com/63842577/153727562-c5cdd5fb-0a36-48fe-bd7e-e5d68746a1dd.png">

**Comment by avipatel91** [comment]
Note that this might lead to a bias.
Examples:

- User sees a clear majority for vote against their own preference. User then thinks it is pointless to vote since their vote won't have an effect on outcome. 

- User sees a clear majority for a vote, and will vote with the crowd.

**Comment by parrot9design** [comment]
This fix won’t introduce any new bias, it just makes the results more accessible to people who click through to view the full proposal when not signed in. It’s one of the most important datapoints on the page, and it’s not visible – even for past votes where bias is irrelevant.

You can already see the percentage approved/rejected when you’re signed in and ready to vote, and thanks to a recent update you can change your vote while the voting window is open, so if someone wants to vote with the crowd, they still will. 

The larger issue of voter apathy/bias is an important one to consider, but if the information is publicly available on the blockchain, would it not be a worse experience to hide it?

**Comment by avipatel91** [comment]
Good points. Since it already exists, then no harm of adding it. 

Right, this was more for discussion than revising feature work. It is an interesting topic, and better suited for the forums. Before we can conclude that there do exist certain biases, a study would have to be done (maybe using A/B testing). But that is out of the scope for this application.
