### ISSUE TITLE
Update the loading spinner on the Trade page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#89]
The code is contained in this commit: https://github.com/balancednetwork/balanced-frontend/pull/4/commits/8c0cd12667bea797856e0122f8bcc79d15038408

Current UI:
<img width="1039" alt="Screen Shot 2021-03-28 at 7 02 45 PM" src="https://user-images.githubusercontent.com/63842577/112743937-3479f000-8ff8-11eb-87e6-9821c0c76ca1.png">

With our code:
<img width="1030" alt="Screen Shot 2021-03-28 at 7 02 31 PM" src="https://user-images.githubusercontent.com/63842577/112743941-4065b200-8ff8-11eb-9018-8d8970f48eb3.png">

**Comment by hetfly** [comment]
@parrot9design  can you provide svg or bigger png please ?

**Comment by parrot9design** [comment]
@hetfly try this:
![loader](https://user-images.githubusercontent.com/63842577/130006736-15a851e4-9afc-4356-a76d-88a617b7a725.png)

I can't give you access to the repo in the original link, but if it helps, these were the related CSS changes:

```
/*
*
* Loader
*
*/

.loader {
	display: block;
	width: 75px;
	margin-left: auto;
	margin-right: auto; 
}
.loader {
    animation-name: spin;
    animation-duration: 30000ms;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
}
@-moz-keyframes spin {
    from { -moz-transform: rotate(0deg); }
    to { -moz-transform: rotate(360deg); }
}
@-webkit-keyframes spin {
    from { -webkit-transform: rotate(0deg); }
    to { -webkit-transform: rotate(360deg); }
}
@keyframes spin {
    from {transform:rotate(0deg);}
    to {transform:rotate(360deg);}
}
```

```
#panel-swap .loader {
	margin-top: 100px;
}
```
