### ISSUE TITLE
Display the price chart according to the right swap pair and time interval.

### ISSUE THREAD

**Issue by WeiLi512** [balancednetwork/balanced-network-interface#9]
Use this price feed API.
http://35.240.219.80:8069/api/v1/chart/lines?symbol=BALNICD&limit=5&order=desc

![image](https://user-images.githubusercontent.com/50083174/110725487-a7dade00-8252-11eb-8ec0-3e348da900c2.png)

Integrate the issue here when it is complete: https://github.com/balancednetwork/balanced-backend/issues/1

**Comment by tuan-tl** [comment]
Updated with this PR https://github.com/balancednetwork/balanced-network-interface/pull/100
