### ISSUE TITLE
Swap Tab: sICX should be tradeable against both bnuSD and ICX

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#91]
ICX needs to be available in this dropdown menu

<img width="372" alt="Screen Shot 2021-03-28 at 1 55 14 AM" src="https://user-images.githubusercontent.com/43685868/112743837-c0443b80-8f68-11eb-9399-77806ba5cf1d.png">

**Comment by tuan-tl** [comment]
fixed with this PR https://github.com/balancednetwork/balanced-network-interface/pull/94
