### ISSUE TITLE
Insufficient error message when withdrawing liquidity

### ISSUE THREAD

**Issue by lijac** [balancednetwork/balanced-network-interface#919]
Error message when withdrawing liquidity.

https://sejong.tracker.solidwallet.io/transaction/0x5c5a5cdd404b190a19bd26de8b382528183215b43689c78cd393823e25163fee

It fails because of the withdrawal lock time. Anyway, the error message doesn't give any clue. (When it fails due to daily DEX rewards distribution, the error message is same)
Are there any possible improvements?

![image](https://user-images.githubusercontent.com/39693487/158450280-13d7ea74-780f-43cb-a94f-5eda595403c1.png)

**Comment by BennyOptions** [comment]
One thing we can try is pointing to tracker.icon.community APIs - I think this has the error message, but not sure. Tracker.icon.foundation removed all custom error messages.

**Comment by BennyOptions** [comment]
Also, this will be solved by the smart contracts in ~2-3 weeks

**Comment by lijac** [comment]
Hope the smart contracts will solve this soon.

**Comment by lijac** [comment]
How are the smart contracts going? @BennyOptions

**Comment by BennyOptions** [comment]
The should be done by the end of this month

**Comment by BennyOptions** [comment]
Closing issue because continuous rewards will fix this
