### ISSUE TITLE
While navigating between pages, the whole page reloads

### ISSUE THREAD

**Issue by lijac** [balancednetwork/balanced-network-interface#921]
Going to Trade page ...
![image](https://user-images.githubusercontent.com/39693487/158455988-b55cfaf3-f84a-47d2-b706-4b18c7748bf0.png)
![image](https://user-images.githubusercontent.com/39693487/158456180-e26498c8-104c-4087-a167-70f03f0a179b.png)

**Comment by lijac** [comment]
@octocat512 what do you think about this?

**Comment by octocat512** [comment]
interesting. you will make it lazy-load only the main part? cool.
