### ISSUE TITLE
Fix issues on the Vote page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-interface#991]
- The indicator to alert users to a new vote no longer appears
- The start of the Approve/Reject bars looks funky in Brave (normal in Firefox & Safari, not sure about Chrome):
![Screen Shot 2022-06-06 at 12 49 48 PM](https://user-images.githubusercontent.com/63842577/172077944-f12a4889-734d-4cd9-8039-16efdae23dc2.png)
![Screen Shot 2022-06-06 at 12 50 26 PM](https://user-images.githubusercontent.com/63842577/172077947-2fce2928-0fcc-496f-ad9d-5b2088c2cbfe.png)

- All votes that have been approved but not enacted via smart contract now say `Voting has ended`. They should say `Approved`.

Another issue that can be tackled separately if necessary: if you're signed in and viewing past votes that you participated in, we should show whether you approved or rejected them.

**Comment by dbrehmer** [comment]
One other change I'd like to see on the vote indicator alert - For addresses with no voting power the alert should not be on. We shouldn't be pestering users to vote if they have no voting power.
