### ISSUE TITLE
Create a "Community List"

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#996]
Consider a community list so new tokens with strong community support can be added to the UI without cluttering the original balanced UI.

![Screen Shot 2022-06-07 at 7.53.25 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/9022e1c1-d6a6-4f00-9186-1e28fcd29c51)

![Screen Shot 2022-06-07 at 7.57.32 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/87f5f847-daa0-46c4-8f88-2075d3f6fb11)

**Comment by parrot9design** [comment]
Keeping the UI "clean" is less of a concern than supporting all assets people want to trade, so a community list will provide a way to do that while somewhat limiting the liability risk. 

Let's reserve the default token list for all tokens Balanced officially supports, and set up a community token list for everything else. We can duplicate the default token list repos and provide a guide for community members to submit a PR for a new community token listing. (Related: https://github.com/balancednetwork/balanced-network-interface/pull/1049, https://github.com/balancednetwork/balanced-network-interface/pull/1030)

It can then be turned on in the UI like so:
<img width="350" alt="community-token-list-option" src="https://user-images.githubusercontent.com/63842577/183546830-04cc76a9-6278-49b5-9610-0082e3577c87.png"><img width="350" alt="community-token-list-modal" src="https://user-images.githubusercontent.com/63842577/183546832-c8e27438-49bd-4124-aadf-b7045d65536e.png">

After you add the list, you should no longer see the text link in the asset selector dropdowns.

Modal content:
```
<div class="modal-content">
	<!-- Overview -->
	<h3 class="label text-center">Add community token list?</h3>
	


	<p class="text-center">The community list contains all popular assets that aren't listed in the app by default.</p><p class="text-center" style="padding-top: 10px;"><a href="">Review the community token list on GitHub.</a></p>
	

	
	<div class="modal-actions">
		<a href="#" class="cancel modal-close">Cancel</a> <a href="./" class="button">Add token list</a>
	</div>
</div>
```


As for how to get an asset added to the default token list (which is where I assume we'd want all BTP-related tokens to be), still thinking this through, but we could consider semi-regular token listing proposals for the community to approve/deny a specific asset or choose their favourite from a poll.
